### ISSUE TITLE
try to call `room.say(urlLink)` but got a "no message rawPayload" rejection error.

### ISSUE THREAD

**Issue by huan** [wechaty/wechaty-puppet-padplus#106]
It happens before, but after I restarted the bot, it's gone.

Today it comes again:
```
2020-01-02T07:55:43.313736+00:00 app[web.1]: 07:55:43 VERB Room say(UrlLink<https://github.com/wechaty/wechaty/issues/1826#issuecomment-570135677>, )
2020-01-02T07:55:43.644179+00:00 app[web.1]: 07:55:43 VERB Message static load(0)
2020-01-02T07:55:43.645203+00:00 app[web.1]: 07:55:43 VERB Message constructor(0) for class Message
2020-01-02T07:55:43.648488+00:00 app[web.1]: 07:55:43 VERB Message ready()
2020-01-02T07:55:43.648822+00:00 app[web.1]: 07:55:43 ERR Chatops wechatyBroadcast() rejection: Error: no message rawPayload
```

I can confirm that the "no message rawPayload" error comes from the wechaty-puppet-padplus module.

P.S. I do not think the `Message static load(0)` is right. Does that mean my message-id is `0` in our padplus module?

**Comment by huan** [comment]
It seems that our GRPC server return a response with message-id = 0, which caused the puppet system problem?

Live logs: <https://dashboard.heroku.com/apps/mike-bo/logs>

**Comment by huan** [comment]
Update: the UrlLinnk function has been recovered now (after 3 hours).

It seems the problem should be one of the following:

1. The server issue has been fixed (by restart maybe)
1. The rate-limit of my Wechat account was reseted. (the rate number/time is unknow yet)

**Comment by huan** [comment]
I ran into this issue again on OSS Bot: this bot has not sent any UrlLink in the past 24 hours at all:

```
2020-01-02T17:33:56.243066+00:00 app[web.1]: 17:33:56 VERB Room say(UrlLink<https://github.com/kaiyuanshe/oss-bot/issues/32#issuecomment-570279337>, )
2020-01-02T17:33:56.605359+00:00 heroku[router]: at=info method=POST path="/" host=oss-bot.kaiyuanshe.cn request_id=23943559-3461-4c89-9524-2899fd2527f1 fwd="192.30.252.90" dyno=web.1 connect=0ms service=386ms status=500 bytes=217 protocol=https
2020-01-02T17:33:56.600604+00:00 app[web.1]: 17:33:56 VERB Message static load(0)
2020-01-02T17:33:56.600735+00:00 app[web.1]: 17:33:56 VERB Message constructor(0) for class Message
2020-01-02T17:33:56.600898+00:00 app[web.1]: 17:33:56 VERB Message ready()
2020-01-02T17:33:56.602911+00:00 app[web.1]: 17:33:56.602Z ERROR event: no message rawPayload (id=7da3ab80-2d85-11ea-8c07-666ca4f72ca0)
2020-01-02T17:33:56.602914+00:00 app[web.1]:   Error: no message rawPayload
2020-01-02T17:33:56.602929+00:00 app[web.1]:       at PuppetPadplus.<anonymous> (/app/node_modules/wechaty/node_modules/wechaty-puppet-padplus/dist/src/puppet-padplus.js:813:23)
2020-01-02T17:33:56.602931+00:00 app[web.1]:       at Generator.next (<anonymous>)
2020-01-02T17:33:56.602933+00:00 app[web.1]:       at fulfilled (/app/node_modules/wechaty/node_modules/wechaty-puppet-padplus/dist/src/puppet-padplus.js:5:58)
2020-01-02T17:33:56.602935+00:00 app[web.1]:       at process._tickCallback (internal/process/next_tick.js:68:7)
```

So it seems not a Wechat Account related problem.

**Comment by su-chang** [comment]
`Message static load(0)` is not right.

It's a server related issue, the msgId in response of room.say() was wrong. Should not be 0.

Could you please show me the parameter of this UrlLink which got 0 as response msgId?

BTW, could you reproduce this issue by the same UrlLink ?

**Comment by huan** [comment]
It's great to know that you confirm this issue is related to the server.

No I cannot reproduce it because it's like sometime work but sometimes not.

But I will post at here if I can find anything useful in the future.

**Comment by su-chang** [comment]
In server end, if they check the parameter for UrlLink is not right and can not send UrlLink message successfully, it will return `0` as response msgId.

So I think we should pay attention to the parameter for UrlLink.

**Comment by huan** [comment]
Today I'm still experiencing this issue:

```
2020-02-07T03:41:59.041418+00:00 app[web.1]: 03:41:59 VERB Room say(UrlLink<https://github.com/wechaty/wechaty/issues/1907#issuecomment-583220305>, )
2020-02-07T03:42:00.240953+00:00 app[web.1]: 03:42:00 VERB Message static load(0)
2020-02-07T03:42:00.242906+00:00 app[web.1]: 03:42:00 VERB Message constructor(0) for class Message
2020-02-07T03:42:00.243211+00:00 app[web.1]: 03:42:00 VERB Message ready()
2020-02-07T03:42:00.243721+00:00 app[web.1]: 03:42:00 ERR Chatops wechatyBroadcast() rejection: Error: no message rawPayload
```
We can see that after we sent a UrlLink, the message id returned 0.

**Comment by windmemory** [comment]
@su-chang Let's throw an error when the messageId is 0? Error makes more sense than a message with id 0.

**Comment by su-chang** [comment]
This issue has already been fixed by https://github.com/wechaty/wechaty-puppet-padplus/pull/125, it will be closed now.
