### ISSUE TITLE
Unpredictable logout event after error puppet-padplus

### ISSUE THREAD

**Issue by maxpaint** [wechaty/wechaty-puppet-padplus#109]
## 1. Versions

- What is your wechaty version?
Answer: "^0.29.8"

- What is your wechaty-puppet-padplus version?
Answer: "0.2.0"

- What is your node version? (run `node --version`)
Answer: node:10
- What OS are you using
Answer: docker image: node:10-slim

## 2. Describe the bug
Got an error from puppet (described below) and then puppet emitted logout event
## 3. To Reproduce
1. run puppet-padplus
2. login
3. send attachment
4. wait for 10 minutes

## 4. Expected behavior

puppet-padplus should stay logged in

## 5. Actual behavior

puppet-padplus receives an error (described below) and emits logout event

## 6. Full Output Logs

<details>
<summary>
Show Logs
</summary>

```shell
PADPLUS_ERROR EXIT 你的微信登录环境存在异常。为了帐号安全，本次登录已失效。 - Error: PADPLUS_ERROR EXIT 你的微信登录环境存在异常。为了帐号安全，本次登录已失效。
    at PuppetPadplus.puppet.on.error (/wechat-cluster/node_modules/wechaty/dist/src/wechaty.js:440:44)
    at PuppetPadplus.emit (events.js:198:13)
    at PuppetPadplus.EventEmitter.emit (domain.js:448:20)
    at PuppetPadplus.emit (/wechat-cluster/node_modules/wechaty-puppet/dist/src/puppet.js:161:22)
    at PadplusManager.manager.on (/wechat-cluster/node_modules/wechaty-puppet-padplus/dist/src/puppet-padplus.js:86:22)
    at PadplusManager.on.args (/wechat-cluster/node_modules/wechaty-puppet-padplus/dist/src/padplus-manager/padplus-manager.js:88:26)
    at PadplusManager.emit (events.js:198:13)
    at PadplusManager.EventEmitter.emit (domain.js:448:20)
    at PadplusManager.emit (/wechat-cluster/node_modules/wechaty-puppet-padplus/dist/src/padplus-manager/padplus-manager.js:82:22)
    at PadplusManager.<anonymous> (/wechat-cluster/node_modules/wechaty-puppet-padplus/dist/src/padplus-manager/padplus-manager.js:433:42)
    at Generator.next (<anonymous>)
    at /wechat-cluster/node_modules/wechaty-puppet-padplus/dist/src/padplus-manager/padplus-manager.js:8:71
    at new WrappedPromise (/wechat-cluster/node_modules/async-listener/es6-wrapped-promise.js:13:18)
    at __awaiter (/wechat-cluster/node_modules/wechaty-puppet-padplus/dist/src/padplus-manager/padplus-manager.js:4:12)
    at GrpcEventEmitter.grpcGatewayEmitter.on (/wechat-cluster/node_modules/wechaty-puppet-padplus/dist/src/padplus-manager/padplus-manager.js:251:53)
    at GrpcEventEmitter.emit (events.js:198:13)
    at GrpcEventEmitter.EventEmitter.emit (domain.js:448:20)
    at GrpcGateway.<anonymous> (/wechat-cluster/node_modules/wechaty-puppet-padplus/dist/src/server-manager/grpc-gateway.js:453:41)
    at Generator.next (<anonymous>)
    at /wechat-cluster/node_modules/wechaty-puppet-padplus/dist/src/server-manager/grpc-gateway.js:8:71
    at new WrappedPromise (/wechat-cluster/node_modules/async-listener/es6-wrapped-promise.js:13:18)
    at __awaiter (/wechat-cluster/node_modules/wechaty-puppet-padplus/dist/src/server-manager/grpc-gateway.js:4:12)
    at ClientReadableStream.stream.on (/wechat-cluster/node_modules/wechaty-puppet-padplus/dist/src/server-manager/grpc-gateway.js:370:41)
    at ClientReadableStream.emit (events.js:198:13)
    at ClientReadableStream.EventEmitter.emit (domain.js:448:20)
    at addChunk (_stream_readable.js:287:12)
    at readableAddChunk (_stream_readable.js:268:11)
    at ClientReadableStream.Readable.push (_stream_readable.js:223:10)
    at Object.onReceiveMessage (/wechat-cluster/node_modules/grpc/src/client_interceptors.js:1263:19)
    at InterceptingListener.recvMessageWithContext (/wechat-cluster/node_modules/grpc/src/client_interceptors.js:607:19)
    at /wechat-cluster/node_modules/grpc/src/client_interceptors.js:707:14
```

</details>

## 7. Additional context
We get this error from time to time. 

[bug]

**Comment by su-chang** [comment]
Duplicated to  this issue: https://github.com/wechaty/wechaty-puppet-padplus/issues/107
