### ISSUE TITLE
UncaughtException: IO error, LOCK: Resource temporarily unavailable

### ISSUE THREAD

**Issue by maxpaint** [wechaty/wechaty-puppet-padplus#112]
## 1. Versions

- What is your wechaty version?
Answer: "^0.29.8"

- What is your wechaty-puppet-padplus version?
Answer: "0.2.0"

- What is your node version? (run `node --version`)
Answer: node:10
- What OS are you using
Answer: docker image: node:10-slim

## 2. Describe the bug
Today we have found many uncaughtException 

## 3. To Reproduce
1. run puppet-padplus
2. login
3. wait 
## 4. Expected behavior
I don't know

## 5. Actual behavior
I don't know
## 6. Full Output Logs
<details>
<summary>
Show Logs
</summary>

```shell
Question: Paste your FULL(DO NOT ONLY PROVIDE FRAGMENTS) log messages
Answer:
uncaughtException: IO error: lock /root/.wechaty/puppet-padplus-cache/flash-store-v0.14/wxid_yhblc3egsy3e22/accound-wxid/LOCK: Resource temporarily unavailable
OpenError: IO error: lock /root/.wechaty/puppet-padplus-cache/flash-store-v0.14/wxid_yhblc3egsy3e22/accound-wxid/LOCK: Resource temporarily unavailable
    at /wechat-cluster/node_modules/levelup/lib/levelup.js:119:23
    at /wechat-cluster/node_modules/abstract-leveldown/abstract-leveldown.js:36:14
    at /wechat-cluster/node_modules/deferred-leveldown/deferred-leveldown.js:31:21
    at /wechat-cluster/node_modules/abstract-leveldown/abstract-leveldown.js:36:14
    at /wechat-cluster/node_modules/rocksdb/node_modules/abstract-leveldown/abstract-leveldown.js:41:14 - 
OpenError: IO error: lock /root/.wechaty/puppet-padplus-cache/flash-store-v0.14/wxid_yhblc3egsy3e22/accound-wxid/LOCK: Resource temporarily unavailable
    at /wechat-cluster/node_modules/levelup/lib/levelup.js:119:23
    at /wechat-cluster/node_modules/abstract-leveldown/abstract-leveldown.js:36:14
    at /wechat-cluster/node_modules/deferred-leveldown/deferred-leveldown.js:31:21
    at /wechat-cluster/node_modules/abstract-leveldown/abstract-leveldown.js:36:14
    at /wechat-cluster/node_modules/rocksdb/node_modules/abstract-leveldown/abstract-leveldown.js:41:14
```

</details>

[bug]

**Comment by su-chang** [comment]
Sorry for response too late.

This problem due to some other Node process are using `flash-store`, please check Node process and then restart again.
