### ISSUE TITLE
`logout()` not work properly

### ISSUE THREAD

**Issue by huan** [wechaty/wechaty-puppet-padplus#168]
If we call `wechaty.logout` with a padplus puppet, then we will see `logout()` will throw an exception

```
09:53:51 VERB Wechaty logout()
09:53:51 VERB PuppetPadplus logout(undefined)
09:53:51 VERB Puppet selfId()
09:53:51 VERB PadplusManager logout()
09:53:51 SILL PadplusUser logout()
09:53:51 SILL RequestClient request()
09:53:51 SILL DedupeApi dedupe() no need to dedupe api 2.
09:53:51 SILL GRPC_GATEWAY GRPC Request ApiType: 2
09:53:52 SILL ==P==A==D==P==L==U==S==<GRPC DATA>==P==A==D==P==L==U==S== 
09:53:52 SILL GRPC_GATEWAY responseType: 13, data : {"code":200,"uin":"3393212435","message":"主动下线成功","mqType":1100}
09:53:52 SILL ==P==A==D==P==L==U==S==<GRPC DATA>==P==A==D==P==L==U==S==
 
09:53:52 SILL PadplusManager Logout WeChat success!
09:53:52 SILL GRPC_GATEWAY stop()
09:53:52 SILL GRPC_GATEWAY GRPC Request ApiType: 5
09:53:57 VERB CacheManager release()
09:53:57 VERB CacheManager releaseCache()
09:53:57 SILL CacheManager releaseCache() closing caches ...
09:53:57 SILL CacheManager releaseCache() cache closed.
09:53:57 VERB PadplusManager logout() finished
09:53:57 VERB Puppet selfId()
09:53:57 SILL Contact ready() @ Puppet#0<PuppetPadplus>(@huan:aka.cn) with id="wxid_dtyu36zm0zz322"
09:53:57 SILL Contact ready() isReady() true
09:53:57 SILL Puppet constructor() this.on(reset) reason: padplus reset
09:53:57 SILL Puppet constructor() resetThrottleQueue.subscribe() reason: padplus reset
09:53:57 VERB Puppet reset(padplus reset)
09:53:57 SILL StateSwitch <PuppetPadplus> off() is false
09:53:57 VERB WechatyManager onLogout(Contact<Elon>)
09:53:57 VERB ContactSelf name()
09:53:57 VERB MiddleManager directMessageToMatrixConsumer("You are now logged out from Wechat. Your user name is: Elon. send `!login` to me to get a new QR Code to scan for logging in.", "Wechaty#ck7aabzw20000yhj27bffdwzb<>(@huan:aka.cn)")
09:53:57 VERB WechatyManager consumerId(Wechaty#ck7aabzw20000yhj27bffdwzb<>(@huan:aka.cn))
09:53:57 VERB AppserviceManager adminRoom(@huan:aka.cn)
09:53:57 VERB AppserviceManager storeQuery(wechatyBridgeRoom, "{"consumerId":"@huan:aka.cn","matrixUserId":"@wechaty:aka.cn"}")
09:53:57 VERB PuppetPadplus stop()
09:53:57 SILL StateSwitch <PuppetPadplus> off() is false
09:53:57 SILL StateSwitch <PuppetPadplus> off() is false
09:53:57 VERB StateSwitch <PuppetPadplus> off(pending) <- (false)
09:53:57 VERB PuppetPadplus logout(logout in wechaty)
09:53:57 VERB Puppet selfId()
09:53:57 INFO Wechaty <wechaty-puppet-padplus> stop() v0.32.2 is stoping ...
09:53:57 SILL StateSwitch <Wechaty> off() is false
09:53:57 SILL StateSwitch <WechatyReady> off() is true
09:53:57 VERB StateSwitch <WechatyReady> off(true) <- (true)
09:53:57 SILL StateSwitch <Wechaty> off() is false
09:53:57 VERB StateSwitch <Wechaty> off(pending) <- (false)
09:53:57 VERB PuppetPadplus stop()
09:53:57 SILL StateSwitch <PuppetPadplus> off() is pending
09:53:57 VERB PuppetPadplus stop() is called on a OFF puppet. await ready(off) and return.
09:53:57 VERB StateSwitch <PuppetPadplus> ready(off, false)
09:53:57 WARN Puppet reset() exception: Error: not logged in, no this.id yet.
09:53:57 ERR Config ###########################
09:53:57 ERR Config unhandledRejection: Error: Error: not logged in, no this.id yet. [object Promise]
09:53:57 ERR Config ###########################
09:53:57 ERR Config process.on(unhandledRejection) promise.catch(Error: not logged in, no this.id yet.)
Config Error: Error: not logged in, no this.id yet.
    at PuppetPadplus.puppet.on.error (/home/huan/chatie/matrix-appservice-wechaty/node_modules/wechaty/src/wechaty.ts:621:32)
    at PuppetPadplus.emit (events.js:198:13)
    at PuppetPadplus.EventEmitter.emit (domain.js:448:20)
    at PuppetPadplus.emit (/home/huan/chatie/matrix-appservice-wechaty/node_modules/wechaty-puppet/src/puppet.ts:287:18)
    at Promise.resolve.then.then.catch.e (/home/huan/chatie/matrix-appservice-wechaty/node_modules/wechaty-puppet/src/puppet.ts:353:14)
(node:126953) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 9)
09:53:57 WARN matrix-appservice-wechaty process.on(warning)
PromiseRejectionHandledWarning
Promise rejection was handled asynchronously (rejection id: 9)
PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 9)
    at handledRejection (internal/process/promises.js:71:23)
    at promiseRejectHandler (internal/process/promises.js:36:14)
    at Promise.then (<anonymous>)
    at Promise.catch (<anonymous>)
    at process.on (/home/huan/chatie/matrix-appservice-wechaty/node_modules/wechaty/src/config.ts:93:18)
    at process.emit (events.js:198:13)
    at process.EventEmitter.emit (domain.js:448:20)
    at process.emit (/home/huan/.nvm/versions/node/v10.18.1/lib/node_modules/ts-node/node_modules/source-map-support/source-map-support.js:485:21)
    at emitPromiseRejectionWarnings (internal/process/promises.js:140:18)
    at process._tickCallback (internal/process/next_tick.js:69:34)
09:53:57 VERB AppserviceManager sendMessage(You are now logged out from Wechat. Your user name is: Elon. send `!login` to me to get a new , !erYMSNMQMbdxoCNkqC:aka.cn)
sendEvent of type m.room.message in !erYMSNMQMbdxoCNkqC:aka.cn with txnId m1583142837862.1
Event sent to !erYMSNMQMbdxoCNkqC:aka.cn with event id $1583142838128jzOLX:aka.cn
09:53:58 INFO Wechaty <wechaty-puppet-padplus> stop() v0.32.2 is stoping ...
09:53:58 SILL StateSwitch <Wechaty> off() is pending
09:53:58 SILL Wechaty stop() on an stopping/stopped instance
09:53:58 VERB StateSwitch <Wechaty> ready(off, false)
```

**Comment by su-chang** [comment]
Already resolved.

**Comment by huan** [comment]
Great to know that, thank you very much!
