### ISSUE TITLE
Error: can not get callback result of GET_CONTACT_SELF_INFO [object Promise]

### ISSUE THREAD

**Issue by huan** [wechaty/wechaty-puppet-padplus#177]
version: `wechaty-puppet-padplus@^0.5.13`

```
02:08:10 INFO Chatops roomMessage(17376996519@chatroom, 🙋)
02:08:10 VERB Chatops queue(,"roomSay")
02:08:10 VERB Room say(🙋, )
02:08:10 VERB Puppet selfId()
02:08:10 VERB PadplusMessage sendMessage()
02:08:10 VERB ContactSelf name()
02:08:10 INFO Chatops roomMessage(5611663299@chatroom, Der! I just got online!
Mike BO v0.4.64)
02:08:10 VERB Chatops queue(,"roomSay")
02:08:10 VERB ContactSelf name()
02:08:10 VERB ContactSelf name()
02:08:10 INFO startBot onLogin(Contact<Huan LI (李卓桓)>) Huan LI (李卓桓) Wechaty(v0.32.2) Heroku Bot(v0.4.64) Getting Started logined
02:08:10 VERB Contact say(Huan LI (李卓桓) Wechaty(v0.32.2) Heroku Bot(v0.4.64) Getting Started logined)
02:08:10 VERB Puppet selfId()
02:08:10 VERB PadplusMessage sendMessage()
02:08:15 VERB Room say(Der! I just got online!
Mike BO v0.4.64, )
02:08:15 VERB Puppet selfId()
02:08:15 VERB PadplusMessage sendMessage()
02:08:41 ERR GRPC_GATEWAY ApiType: 17 request timeout, traceId: 6b626b0f-5cc4-43dd-8cef-84f7c892ec7a
02:08:41 ERR Config ###########################
02:08:41 ERR Config unhandledRejection: Error: can not get callback result of GET_CONTACT_SELF_INFO [object Promise]
02:08:41 ERR Config ###########################
02:08:41 ERR Config process.on(unhandledRejection) promise.catch(can not get callback result of GET_CONTACT_SELF_INFO)
Config Error: can not get callback result of GET_CONTACT_SELF_INFO
    at PadplusContact.<anonymous> (/app/node_modules/wechaty-puppet-padplus/src/padplus-manager/api-request/contact.ts:293:13)
    at Generator.next (<anonymous>)
    at fulfilled (/app/node_modules/wechaty-puppet-padplus/dist/src/padplus-manager/api-request/contact.js:5:58)
(node:4) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 2)
02:09:42 VERB PadplusManager setContactAndRoomData() more than 1 minutes no change on data, emit ready event.
02:09:42 INFO Chatops roomMessage(17376996519@chatroom, 💪)
02:09:42 VERB Chatops queue(,"roomSay")
02:09:42 VERB Room say(💪, )
02:09:42 VERB Puppet selfId()
02:09:42 VERB PadplusMessage sendMessage()
02:09:42 VERB StateSwitch <WechatyReady> on(true) <- (false)
```

### Update

The padplus keep thinking that I have logged in even after I logged out my ipad login from my phone wechat app.

**Comment by su-chang** [comment]
Thanks for your issue.

For `Error: can not get callback result of GET_CONTACT_SELF_INFO`:
> I think its some wrong with the server login status.

For `version: wechaty-puppet-padplus@^0.5.13`:
> The bug which you have found has been fixed, related issue: https://github.com/wechaty/wechaty-puppet-padplus/issues/168, so I think you should update `wechaty-puppet-padplus`

**Comment by su-chang** [comment]
When we init the padplus, here are some logs about the first request to grpc server :
```js
10:38:31 SILL PadplusManager uin : 289099750
10:38:32 SILL PadplusUser initInstance()
10:38:32 SILL RequestClient request()
10:38:32 SILL DedupeApi dedupe() no need to dedupe api 3.
10:38:32 SILL GRPC_GATEWAY GRPC Request ApiType: 3
10:38:32 SILL ==P==A==D==P==L==U==S==<GRPC DATA>==P==A==D==P==L==U==S==
10:38:32 SILL GRPC_GATEWAY responseType: 15, data : {"uin":289099750,"online":true,"wechatUser":{"headImgUrl":"http://wx.qlogo.cn/mmhead/ver_1/jZ34QmkrEg1RCCGTfj8cQseXHwYmib1JS6BTicpVYPu0HxWxaQxWeHrubUyyrBMeESnAhUP18pEwadkazdJnBsibcDPJbDGHBSw9MNqETHxk3CLotw7LSYQg5wV5B3RnDo5/0","nickName":"jessicaTu","uin":289099750,"userName":"wxid_orp7dihe2pm112","alias":"juzi_bot","verifyFlag":0}}
10:38:32 SILL ==P==A==D==P==L==U==S==<GRPC DATA>==P==A==D==P==L==U==S==
```

we can found that `"uin":289099750,"online":true,` but when we send the next request for `GET_CONTACT_SELF_INFO ` the grpc has no response for it, maybe the server think the bot is offline.

So I guess there some bugs about sync login data in base server. Im checking...

**Comment by huan** [comment]
Thanks for the reply.

I have upgraded the padplus to the latest. However, I'm still experiencing that I can not log out my Wechaty bot for padplus: I have already logged it out from my Phone, but the bot keep thinking it was logged in but it just can not do anything.

**Comment by su-chang** [comment]
Please remove `xxx.memory-card.json`, and then restart the bot again.

**Comment by huan** [comment]
Thanks for the reply. I had resolved this problem by changing to another token.
