### ISSUE TITLE
[Server Error] GRPC_GATEWAY Error: 13 INTERNAL: Failed to parse server response

### ISSUE THREAD

**Issue by lijiarui** [wechaty/wechaty-puppet-padplus#21]
```
22:46:12 ERR GRPC_GATEWAY Error: 13 INTERNAL: Failed to parse server response
    at Object.exports.createStatusError (/Users/jiaruili/git/padplus/node_modules/grpc/src/common.js:91:15)
    at ClientReadableStream._emitStatusIfDone (/Users/jiaruili/git/padplus/node_modules/grpc/src/client.js:233:26)
    at ClientReadableStream._receiveStatus (/Users/jiaruili/git/padplus/node_modules/grpc/src/client.js:211:8)
    at Object.onReceiveStatus (/Users/jiaruili/git/padplus/node_modules/grpc/src/client_interceptors.js:1272:15)
    at InterceptingListener._callNext (/Users/jiaruili/git/padplus/node_modules/grpc/src/client_interceptors.js:568:42)
    at InterceptingListener.onReceiveStatus (/Users/jiaruili/git/padplus/node_modules/grpc/src/client_interceptors.js:618:8)
    at /Users/jiaruili/git/padplus/node_modules/grpc/src/client_interceptors.js:1029:24
```

**Comment by lijiarui** [comment]
After receiving this error, the bot can’t receive any message anymore.

**Comment by windmemory** [comment]
This needs more investigation. Will do this later.

**Comment by su-chang** [comment]
Already resolved.

Please update `wechaty-puppet-padplus`
