### ISSUE TITLE
timeout logout

### ISSUE THREAD

**Issue by typedef** [wechaty/wechaty-puppet-padplus#234]
> Important：Please file the issue follow the template, or we won't help you to solve the problem.

## 0. Report Issue Guide

1. Please run the following command and check whether the problem has been fixed：

```
npm install wechaty-puppet-padlus@next
```

2. Please search in the issue first, and make sure your problem had not been reported before

## 1. Versions

- What is your wechaty version?
Answer:

- What is your wechaty-puppet-padplus version?
Answer:

- What is your node version? (run `node --version`)
Answer:

- What os are you using
Answer:

## 2. Describe the bug

Give a clear and concise description of what the bug is.

## 3. To Reproduce

This part is very important: if you can not provide any reproduce steps, then the problem will be very hard to be recognized.

1. run '...'
2. ...
3. ...

## 4. Expected behavior

Give a clear and concise description of what you expected to happen.

## 5. Actual behavior

If applicable, add screenshots to help explain your problem. But do not paste log screenshots here.

## 6. Full Output Logs

Set env `WECHATY_LOG=silly` in order to set log level to silly, then we can get the full log (If you dosen't set log env, log level is info as default, we cannot get the full log)

**We need full log instead of log screenshot or log fragments!**

<details>
10:08:10 WARN Puppet constructor() watchdog.on(reset) reason: {"data":"3b9c6dc3-f17a-421b-8bae-efad66d6c84b","timeout":60000}
10:08:10 INFO PuppetPadplus stop()
10:08:10 INFO PuppetPadplus logout(true, logout in wechaty)
Contact<Glorynotify> logout
10:08:15 INFO PuppetPadplus start()
User Contact<Glorynotify> logined

<summary>
Show Logs
</summary>

```shell
$ WECHATY_LOG=silly node yourbot.js

Question: Paste your FULL(DO NOT ONLY PROVIDE FRAGMENTS) log messages
Answer:

```

</details>

## 7. Additional context

[bug]

**Comment by typedef** [comment]
10:08:10 WARN Puppet constructor() watchdog.on(reset) reason: {"data":"3b9c6dc3-f17a-421b-8bae-efad66d6c84b","timeout":60000}
10:08:10 INFO PuppetPadplus stop()
10:08:10 INFO PuppetPadplus logout(true, logout in wechaty)
Contact<Glorynotify> logout
10:08:15 INFO PuppetPadplus start()
User Contact<Glorynotify> logined

**Comment by su-chang** [comment]
Sorry, could you please obey the issue rules?

If you want to get help, please pay more time on this issue.

An easy way for you: upgrade `wechaty@next` and `wechaty-puppet-padplus@next`.

**Comment by simai2019** [comment]
Same error today:
![image](https://user-images.githubusercontent.com/48561629/80425883-27034400-8917-11ea-9396-13e0bc54a475.png)
app_1  | 01:04:43 WARN Puppet constructor() watchdog.on(reset) reason: {"data":"","timeout":60000}
```
app_1  | 00:34:53 INFO Wechaty <Puppet#0<PuppetPadplus>()>(grace) start() v0.38.4 is starting...
app_1  | 00:36:29 INFO Contact<AI机器人> login
app_1  | 00:36:29 INFO Schedule tasks inited.
app_1  | 00:36:30 INFO Bot Started.
app_1  | 00:38:05 INFO onReady
app_1  | 00:38:05 ERR onReady undefined
app_1  | 00:38:06 INFO onReady Now you can use Global.allRooms instead of bot.Room.findAll(): Room<Source群>,Room<西奈山jh>,Room<活水>,Room<诗篇群发源>,Room<主人0421>,Room<西罗亚小组>,Room<活水工人>,Room<西三旗交流群>
app_1  | 00:39:50 ERR GRPC_GATEWAY ApiType: 6 request timeout, traceId: 33329d86-e40a-4b74-9d70-bde59c0e8c8a
app_1  | 00:39:50 ERR GRPC_GATEWAY can not get heartbeat from grpc server
app_1  | 00:39:50 ERR GRPC_GATEWAY ApiType: 6 request timeout, traceId: c1c99261-52ca-44c1-add0-8cd8bc2edc62
app_1  | 00:39:50 ERR GRPC_GATEWAY can not get heartbeat from grpc server
app_1  | 01:00:20 WARN Puppet constructor() watchdog.on(reset) reason: {"data":"d1d5738c-8cdd-4258-a82a-475d8954a68e","timeout":60000}
app_1  | 01:00:20 INFO StarterBot Contact<AI机器人> logout
app_1  | 01:00:37 WARN Puppet reset() exception: Error: can not get callback result of INIT
app_1  | (node:18) UnhandledPromiseRejectionWarning: Error:
app_1  |     at PuppetPadplus.<anonymous> (/usr/src/app/node_modules/wechaty/src/wechaty.ts:621:32)
app_1  |     at PuppetPadplus.emit (events.js:315:20)
app_1  |     at PuppetPadplus.EventEmitter.emit (domain.js:485:12)
app_1  |     at PuppetPadplus.emit (/usr/src/app/node_modules/wechaty-puppet/src/puppet.ts:307:18)
app_1  |     at /usr/src/app/node_modules/wechaty-puppet/src/puppet.ts:386:14
app_1  | (Use `node --trace-warnings ...` to show where the warning was created)
app_1  | (node:18) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
app_1  | (node:18) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
app_1  | 01:00:47 INFO PadplusManager start grpc gateway failed for reason: Error: Try to connect to server timeout., retry start in 5 seconds.
app_1  | (node:18) UnhandledPromiseRejectionWarning: Error: can not get callback result of INIT
app_1  |     at PadplusUser.<anonymous> (/usr/src/app/node_modules/wechaty-puppet-padplus/src/padplus-manager/api-request/user.ts:23:13)
app_1  |     at Generator.next (<anonymous>)
app_1  |     at fulfilled (/usr/src/app/node_modules/wechaty-puppet-padplus/dist/src/padplus-manager/api-request/user.js:5:58)
app_1  | (node:18) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 6)
app_1  | (node:18) UnhandledPromiseRejectionWarning: Error: can not get callback result of INIT
app_1  |     at PadplusUser.<anonymous> (/usr/src/app/node_modules/wechaty-puppet-padplus/src/padplus-manager/api-request/user.ts:23:13)
app_1  |     at Generator.next (<anonymous>)
app_1  |     at fulfilled (/usr/src/app/node_modules/wechaty-puppet-padplus/dist/src/padplus-manager/api-request/user.js:5:58)
app_1  | (node:18) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 8)
app_1  | 01:01:19 ERR GRPC_GATEWAY ApiType: 6 request timeout, traceId: 5b9c63e5-6687-4d81-a846-ebc458839888
app_1  | 01:01:19 ERR GRPC_GATEWAY can not get heartbeat from grpc server
app_1  | 01:01:27 INFO PadplusManager start grpc gateway failed for reason: Error: Try to connect to server timeout., retry start in 5 seconds.
app_1  | (node:18) UnhandledPromiseRejectionWarning: Error: can not get callback result of INIT
app_1  |     at PadplusUser.<anonymous> (/usr/src/app/node_modules/wechaty-puppet-padplus/src/padplus-manager/api-request/user.ts:23:13)
app_1  |     at Generator.next (<anonymous>)
app_1  |     at fulfilled (/usr/src/app/node_modules/wechaty-puppet-padplus/dist/src/padplus-manager/api-request/user.js:5:58)
app_1  | (node:18) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 11)
app_1  | (node:18) UnhandledPromiseRejectionWarning: Error: can not get callback result of INIT
app_1  |     at PadplusUser.<anonymous> (/usr/src/app/node_modules/wechaty-puppet-padplus/src/padplus-manager/api-request/user.ts:23:13)
app_1  |     at Generator.next (<anonymous>)
app_1  |     at fulfilled (/usr/src/app/node_modules/wechaty-puppet-padplus/dist/src/padplus-manager/api-request/user.js:5:58)
app_1  | (node:18) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 13)
app_1  | (node:18) UnhandledPromiseRejectionWarning: Error: can not get callback result of INIT
app_1  |     at PadplusUser.<anonymous> (/usr/src/app/node_modules/wechaty-puppet-padplus/src/padplus-manager/api-request/user.ts:23:13)
app_1  |     at Generator.next (<anonymous>)
app_1  |     at fulfilled (/usr/src/app/node_modules/wechaty-puppet-padplus/dist/src/padplus-manager/api-request/user.js:5:58)
app_1  | (node:18) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 15)
app_1  | (node:18) UnhandledPromiseRejectionWarning: Error: can not get callback result of INIT
app_1  |     at PadplusUser.<anonymous> (/usr/src/app/node_modules/wechaty-puppet-padplus/src/padplus-manager/api-request/user.ts:23:13)
app_1  |     at Generator.next (<anonymous>)
app_1  |     at fulfilled (/usr/src/app/node_modules/wechaty-puppet-padplus/dist/src/padplus-manager/api-request/user.js:5:58)
app_1  | (node:18) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 17)
```

**Comment by su-chang** [comment]
> 01:00:37 WARN Puppet reset() exception: Error: can not get callback result of INIT

Can you make sure your network are all right? It seems that your bot disconnect with network.

`WECHATY_LOG=silly node index.js`, this command could help you to get detail logs about this problem.
