### ISSUE TITLE
after login in wechaty, some xml message parse error

### ISSUE THREAD

**Issue by su-chang** [wechaty/wechaty-puppet-padplus#298]
> Important：Please file the issue follow the template, or we won't help you to solve the problem.

## 0. Report Issue Guide

1. Please run the following command and check whether the problem has been fixed：

```
npm install wechaty-puppet-padlus@next
```

2. Please search in the issue first, and make sure your problem had not been reported before

## 1. Versions

- What is your wechaty version?
Answer:0.47.8

- What is your wechaty-puppet-padplus version?
Answer:0.7.36

- What is your node version? (run `node --version`)
Answer:10.16.0

- What os are you using
Answer:Mac OS

## 2. Describe the bug

Give a clear and concise description of what the bug is.

When the bot login and it will received some new type messages and can not parse right.

## 3. To Reproduce

This part is very important: if you can not provide any reproduce steps, then the problem will be very hard to be recognized.

1. login the bot
2. the bot will received some messages which type is 10002
3. this message can not parse right

## 4. Expected behavior

Give a clear and concise description of what you expected to happen.

## 5. Actual behavior

If applicable, add screenshots to help explain your problem. But do not paste log screenshots here.

## 6. Full Output Logs

Set env `WECHATY_LOG=silly` in order to set log level to silly, then we can get the full log (If you dosen't set log env, log level is info as default, we cannot get the full log)

**We need full log instead of log screenshot or log fragments!**

<details>
<summary>
Show Logs
</summary>

```shell
$ WECHATY_LOG=silly node yourbot.js

Question: Paste your FULL(DO NOT ONLY PROVIDE FRAGMENTS) log messages
Answer:
09:39:11 SILL PuppetPadplus contactRawPayloadParser()

    ============================================
    user : Contact<jessicaTu>, login success. wxid: wxid_orp7dihe2pm112, accont: juzi_bot
    ============================================

09:39:12 SILL ==P==A==D==P==L==U==S==<GRPC DATA>==P==A==D==P==L==U==S==
09:39:12 SILL GRPC_GATEWAY responseType: MESSAGE_RECEIVE, data : {"Status":3,"CreateTime":1597801129001,"NewMsgId":1597212004,"msgSourceCd":2,"ToUserName":"wxid_orp7dihe2pm112","MsgType":10002,"L1MsgType":5,"ImgStatus":1,"wechatUserName":"wxid_orp7dihe2pm112","MsgId":"1597212004","MsgSource":"","PushContent":"","ImgBuf":"","Content":"<sysmsg type=\"functionmsg\">\n<functionmsg>\n<cgi>/cgi-bin/micromsg-bin/pullfunctionmsg</cgi>\n<cmdid>614</cmdid>\n<functionmsgid>MMKANYIKAN_REDDOT_1597212300</functionmsgid>\n<retryinterval>150</retryinterval>\n<retrycount>3</retrycount>\n<custombuff>YImkAXIKMTU5NzIxMjMwMHoGd2VpeGluigEcTU1LQU5ZSUtBTl9SRURET1RfMTU5NzIxMjMwMKoBWHBlTUhiTDIvWHhTK1JZcldNTmtMeFdFRWpjY1gvNkErN0VoUHcyR0VrcCtOSTBrUVR1eGtJTXdMUFZyR3gvZWwvZDVZZE9lVVVadWRGTVl3NVJpMHJBPT0=</custombuff>\n<businessid>21001</businessid>\n<actiontime>1597212004</actiontime>\n<functionmsgversion>2</functionmsgversion>\n</functionmsg>\n</sysmsg>","FromUserName":"weixin","Uin":"289099750"}
09:39:12 SILL ==P==A==D==P==L==U==S==<GRPC DATA>==P==A==D==P==L==U==S==

09:39:12 SILL ==P==A==D==P==L==U==S==<GRPC DATA>==P==A==D==P==L==U==S==
09:39:12 SILL GRPC_GATEWAY responseType: MESSAGE_RECEIVE, data : {"Status":3,"CreateTime":1597801129002,"NewMsgId":1597240807,"msgSourceCd":2,"ToUserName":"wxid_orp7dihe2pm112","MsgType":10002,"L1MsgType":5,"ImgStatus":1,"wechatUserName":"wxid_orp7dihe2pm112","MsgId":"1597240807","MsgSource":"","PushContent":"","ImgBuf":"","Content":"<sysmsg type=\"functionmsg\">\n<functionmsg>\n<cgi>/cgi-bin/micromsg-bin/pullfunctionmsg</cgi>\n<cmdid>614</cmdid>\n<functionmsgid>MMKANYIKAN_JINGXUANREDDOT_1597241100</functionmsgid>\n<retryinterval>150</retryinterval>\n<retrycount>3</retrycount>\n<custombuff>YIqkAXIKMTU5NzI0MTEwMHoGd2VpeGluigEkTU1LQU5ZSUtBTl9KSU5HWFVBTlJFRERPVF8xNTk3MjQxMTAwqgFsN25HMjU1eU00aVJqNjVRZkdpelgraDFwNTVnWU5mVmtiaDB0NEoyRHhTbTA1S2lLa1NteG9NNDRZTk0wMXdBc1FLMXRHS2xFYlAwMlBNLzdaekVmcGVyaFg1eDEyc0ljRm5zRUFhaFBWSlE9</custombuff>\n<businessid>21002</businessid>\n<actiontime>1597240807</actiontime>\n<functionmsgversion>2</functionmsgversion>\n</functionmsg>\n</sysmsg>","FromUserName":"weixin","Uin":"289099750"}
09:39:12 SILL ==P==A==D==P==L==U==S==<GRPC DATA>==P==A==D==P==L==U==S==

09:39:12 SILL ==P==A==D==P==L==U==S==<GRPC DATA>==P==A==D==P==L==U==S==
09:39:12 SILL GRPC_GATEWAY responseType: MESSAGE_RECEIVE, data : {"Status":3,"CreateTime":1597801129003,"NewMsgId":1597298405,"msgSourceCd":2,"ToUserName":"wxid_orp7dihe2pm112","MsgType":10002,"L1MsgType":5,"ImgStatus":1,"wechatUserName":"wxid_orp7dihe2pm112","MsgId":"1597298405","MsgSource":"","PushContent":"","ImgBuf":"","Content":"<sysmsg type=\"functionmsg\">\n<functionmsg>\n<cgi>/cgi-bin/micromsg-bin/pullfunctionmsg</cgi>\n<cmdid>614</cmdid>\n<functionmsgid>MMKANYIKAN_REDDOT_1597298700</functionmsgid>\n<retryinterval>150</retryinterval>\n<retrycount>3</retrycount>\n<custombuff>YImkAXIKMTU5NzI5ODcwMHoGd2VpeGluigEcTU1LQU5ZSUtBTl9SRURET1RfMTU5NzI5ODcwMKoBWDcxek83TjdNcmkvcjNzVVFPRUZFd1hwZkEvV0xrQ0dkVXNkRVd3RU9mU1duRUh3N0loNi9XOVQ4MXZmQndwOUJZbXNkR3F0QWR5TXdxSDRoS1NDNzBBPT0=</custombuff>\n<businessid>21001</businessid>\n<actiontime>1597298405</actiontime>\n<functionmsgversion>2</functionmsgversion>\n</functionmsg>\n</sysmsg>","FromUserName":"weixin","Uin":"289099750"}
09:39:12 SILL ==P==A==D==P==L==U==S==<GRPC DATA>==P==A==D==P==L==U==S==

09:39:12 SILL ==P==A==D==P==L==U==S==<GRPC DATA>==P==A==D==P==L==U==S==
09:39:12 SILL GRPC_GATEWAY responseType: MESSAGE_RECEIVE, data : {"Status":3,"CreateTime":1597801129004,"NewMsgId":1597327209,"msgSourceCd":2,"ToUserName":"wxid_orp7dihe2pm112","MsgType":10002,"L1MsgType":5,"ImgStatus":1,"wechatUserName":"wxid_orp7dihe2pm112","MsgId":"1597327209","MsgSource":"","PushContent":"","ImgBuf":"","Content":"<sysmsg type=\"functionmsg\">\n<functionmsg>\n<cgi>/cgi-bin/micromsg-bin/pullfunctionmsg</cgi>\n<cmdid>614</cmdid>\n<functionmsgid>MMKANYIKAN_JINGXUANREDDOT_1597327500</functionmsgid>\n<retryinterval>150</retryinterval>\n<retrycount>3</retrycount>\n<custombuff>YIqkAXIKMTU5NzMyNzUwMHoGd2VpeGluigEkTU1LQU5ZSUtBTl9KSU5HWFVBTlJFRERPVF8xNTk3MzI3NTAwqgFsWVlCc3hHYUUzakFFSlh2aUtsTHl6MW4va09KaHpkUFJpdmF4UkRhMm1YTmlOcSt5d1JyMlpsSEcyYXJRUlpCZFlQeU4yU2tNbFpFM1FIRXM3MFpFVWduOG1hOXFpZmhXeUtzY3ZnVHN1ZEE9</custombuff>\n<businessid>21002</businessid>\n<actiontime>1597327208</actiontime>\n<functionmsgversion>2</functionmsgversion>\n</functionmsg>\n</sysmsg>","FromUserName":"weixin","Uin":"289099750"}
09:39:12 SILL ==P==A==D==P==L==U==S==<GRPC DATA>==P==A==D==P==L==U==S==

09:39:12 SILL ==P==A==D==P==L==U==S==<GRPC DATA>==P==A==D==P==L==U==S==
09:39:12 SILL GRPC_GATEWAY responseType: MESSAGE_RECEIVE, data : {"Status":3,"CreateTime":1597801129005,"NewMsgId":1597384808,"msgSourceCd":2,"ToUserName":"wxid_orp7dihe2pm112","MsgType":10002,"L1MsgType":5,"ImgStatus":1,"wechatUserName":"wxid_orp7dihe2pm112","MsgId":"1597384808","MsgSource":"","PushContent":"","ImgBuf":"","Content":"<sysmsg type=\"functionmsg\">\n<functionmsg>\n<cgi>/cgi-bin/micromsg-bin/pullfunctionmsg</cgi>\n<cmdid>614</cmdid>\n<functionmsgid>MMKANYIKAN_REDDOT_1597385100</functionmsgid>\n<retryinterval>150</retryinterval>\n<retrycount>3</retrycount>\n<custombuff>YImkAXIKMTU5NzM4NTEwMHoGd2VpeGluigEcTU1LQU5ZSUtBTl9SRURET1RfMTU5NzM4NTEwMKoBWCtyT3E3N0gxclBXWExTZHY5T0MwbElMNnBYREtEOVZnZzExdzk3SHZwUmdscnN1elNxS1NRNkR0R1RqL2QrUXliK3daMy9WTmUrZEFDTm9Sc0NHb2NBPT0=</custombuff>\n<businessid>21001</businessid>\n<actiontime>1597384808</actiontime>\n<functionmsgversion>2</functionmsgversion>\n</functionmsg>\n</sysmsg>","FromUserName":"weixin","Uin":"289099750"}
09:39:12 SILL ==P==A==D==P==L==U==S==<GRPC DATA>==P==A==D==P==L==U==S==

09:39:12 SILL ==P==A==D==P==L==U==S==<GRPC DATA>==P==A==D==P==L==U==S==
09:39:12 SILL GRPC_GATEWAY responseType: MESSAGE_RECEIVE, data : {"Status":3,"CreateTime":1597801129006,"NewMsgId":1597413600,"msgSourceCd":2,"ToUserName":"wxid_orp7dihe2pm112","MsgType":10002,"L1MsgType":5,"ImgStatus":1,"wechatUserName":"wxid_orp7dihe2pm112","MsgId":"1597413600","MsgSource":"","PushContent":"","ImgBuf":"","Content":"<sysmsg type=\"functionmsg\">\n<functionmsg>\n<cgi>/cgi-bin/micromsg-bin/pullfunctionmsg</cgi>\n<cmdid>614</cmdid>\n<functionmsgid>MMKANYIKAN_JINGXUANREDDOT_1597413900</functionmsgid>\n<retryinterval>150</retryinterval>\n<retrycount>3</retrycount>\n<custombuff>YIqkAXIKMTU5NzQxMzkwMHoGd2VpeGluigEkTU1LQU5ZSUtBTl9KSU5HWFVBTlJFRERPVF8xNTk3NDEzOTAwqgFsTis3NmxzckUrOFYrUjFMOEpweFRvbk1UYTV3YzdGVEIzODhYenVvVU1HeFpTNDJCemNCc09lNXdqM0llRzZjcHhoS1N5SkpCT3RKSzcvK2t4T1hGNk50ZVNYUHEwVUM3aHhKZ0lIV0UxMjQ9</custombuff>\n<businessid>21002</businessid>\n<actiontime>1597413600</actiontime>\n<functionmsgversion>2</functionmsgversion>\n</functionmsg>\n</sysmsg>","FromUserName":"weixin","Uin":"289099750"}
09:39:12 SILL ==P==A==D==P==L==U==S==<GRPC DATA>==P==A==D==P==L==U==S==

09:39:12 SILL ==P==A==D==P==L==U==S==<GRPC DATA>==P==A==D==P==L==U==S==
09:39:12 SILL GRPC_GATEWAY responseType: MESSAGE_RECEIVE, data : {"Status":3,"CreateTime":1597801129007,"NewMsgId":1597471210,"msgSourceCd":2,"ToUserName":"wxid_orp7dihe2pm112","MsgType":10002,"L1MsgType":5,"ImgStatus":1,"wechatUserName":"wxid_orp7dihe2pm112","MsgId":"1597471210","MsgSource":"","PushContent":"","ImgBuf":"","Content":"<sysmsg type=\"functionmsg\">\n<functionmsg>\n<cgi>/cgi-bin/micromsg-bin/pullfunctionmsg</cgi>\n<cmdid>614</cmdid>\n<functionmsgid>MMKANYIKAN_REDDOT_1597471500</functionmsgid>\n<retryinterval>150</retryinterval>\n<retrycount>3</retrycount>\n<custombuff>YImkAXIKMTU5NzQ3MTUwMHoGd2VpeGluigEcTU1LQU5ZSUtBTl9SRURET1RfMTU5NzQ3MTUwMKoBWDlnUjQwcnlYdlpCeFVISXBlQ1F0M25pTzJHTUZhcWhFNkEyT3I3S0Z2eFZjcGZUdC9MTHhWUFQ1aStYbVdpd3JTL0M5S1lIaDBsc0xKWXJKR1BDb25RPT0=</custombuff>\n<businessid>21001</businessid>\n<actiontime>1597471210</actiontime>\n<functionmsgversion>2</functionmsgversion>\n</functionmsg>\n</sysmsg>","FromUserName":"weixin","Uin":"289099750"}
09:39:12 SILL ==P==A==D==P==L==U==S==<GRPC DATA>==P==A==D==P==L==U==S==

09:39:12 SILL ==P==A==D==P==L==U==S==<GRPC DATA>==P==A==D==P==L==U==S==
09:39:12 SILL GRPC_GATEWAY responseType: MESSAGE_RECEIVE, data : {"Status":3,"CreateTime":1597801129008,"NewMsgId":1597500002,"msgSourceCd":2,"ToUserName":"wxid_orp7dihe2pm112","MsgType":10002,"L1MsgType":5,"ImgStatus":1,"wechatUserName":"wxid_orp7dihe2pm112","MsgId":"1597500002","MsgSource":"","PushContent":"","ImgBuf":"","Content":"<sysmsg type=\"functionmsg\">\n<functionmsg>\n<cgi>/cgi-bin/micromsg-bin/pullfunctionmsg</cgi>\n<cmdid>614</cmdid>\n<functionmsgid>MMKANYIKAN_JINGXUANREDDOT_1597500300</functionmsgid>\n<retryinterval>150</retryinterval>\n<retrycount>3</retrycount>\n<custombuff>YIqkAXIKMTU5NzUwMDMwMHoGd2VpeGluigEkTU1LQU5ZSUtBTl9KSU5HWFVBTlJFRERPVF8xNTk3NTAwMzAwqgFsalJEbHZGQi9uRmtRbHk5QlhKNzlPd05lT2xXNE9Cd3hCbUVRYUZ0aEtpTDVqdzF2YW90QjFRdlhzN1p6OGVTdGEwTjdETnh2NndCdmJaa1I1SXFKQks3K1hZSnM5dEJPNGJsVmwva1Z0WUE9</custombuff>\n<businessid>21002</businessid>\n<actiontime>1597500002</actiontime>\n<functionmsgversion>2</functionmsgversion>\n</functionmsg>\n</sysmsg>","FromUserName":"weixin","Uin":"289099750"}
09:39:12 SILL ==P==A==D==P==L==U==S==<GRPC DATA>==P==A==D==P==L==U==S==

09:39:12 SILL ==P==A==D==P==L==U==S==<GRPC DATA>==P==A==D==P==L==U==S==
09:39:12 SILL GRPC_GATEWAY responseType: MESSAGE_RECEIVE, data : {"Status":3,"CreateTime":1597801129009,"NewMsgId":1597557600,"msgSourceCd":2,"ToUserName":"wxid_orp7dihe2pm112","MsgType":10002,"L1MsgType":5,"ImgStatus":1,"wechatUserName":"wxid_orp7dihe2pm112","MsgId":"1597557600","MsgSource":"","PushContent":"","ImgBuf":"","Content":"<sysmsg type=\"functionmsg\">\n<functionmsg>\n<cgi>/cgi-bin/micromsg-bin/pullfunctionmsg</cgi>\n<cmdid>614</cmdid>\n<functionmsgid>MMKANYIKAN_REDDOT_1597557900</functionmsgid>\n<retryinterval>150</retryinterval>\n<retrycount>3</retrycount>\n<custombuff>YImkAXIKMTU5NzU1NzkwMHoGd2VpeGluigEcTU1LQU5ZSUtBTl9SRURET1RfMTU5NzU1NzkwMKoBWFZiQzBrMmRST3NDVEZCalh2Tm1zR0pZR3NOREpxcDZ5c0p5SG12Q21TUmZGWlc4ZU1IOGRKYStNVUdCMHBvOVRJNTlxd1ZYbHFlUjdiUjB4a2tkWUxnPT0=</custombuff>\n<businessid>21001</businessid>\n<actiontime>1597557600</actiontime>\n<functionmsgversion>2</functionmsgversion>\n</functionmsg>\n</sysmsg>","FromUserName":"weixin","Uin":"289099750"}
09:39:12 SILL ==P==A==D==P==L==U==S==<GRPC DATA>==P==A==D==P==L==U==S==

09:39:12 SILL ==P==A==D==P==L==U==S==<GRPC DATA>==P==A==D==P==L==U==S==
09:39:12 SILL GRPC_GATEWAY responseType: MESSAGE_RECEIVE, data : {"Status":3,"CreateTime":1597801129010,"NewMsgId":1597586403,"msgSourceCd":2,"ToUserName":"wxid_orp7dihe2pm112","MsgType":10002,"L1MsgType":5,"ImgStatus":1,"wechatUserName":"wxid_orp7dihe2pm112","MsgId":"1597586403","MsgSource":"","PushContent":"","ImgBuf":"","Content":"<sysmsg type=\"functionmsg\">\n<functionmsg>\n<cgi>/cgi-bin/micromsg-bin/pullfunctionmsg</cgi>\n<cmdid>614</cmdid>\n<functionmsgid>MMKANYIKAN_JINGXUANREDDOT_1597586700</functionmsgid>\n<retryinterval>150</retryinterval>\n<retrycount>3</retrycount>\n<custombuff>YIqkAXIKMTU5NzU4NjcwMHoGd2VpeGluigEkTU1LQU5ZSUtBTl9KSU5HWFVBTlJFRERPVF8xNTk3NTg2NzAwqgFsbm1LbitVcWxHTjdUVFBkMUxoVDRmTzd6NTFnMVo3SDlMYk84TTk1cDZUUC9zYVJqeTdsbmhncS8wN0RaaEowT1RtWTNXazhnYzNtVUl0RWRncldiOWozQVcxODV1M3g5RUYvWitxbUtnNVU9</custombuff>\n<businessid>21002</businessid>\n<actiontime>1597586403</actiontime>\n<functionmsgversion>2</functionmsgversion>\n</functionmsg>\n</sysmsg>","FromUserName":"weixin","Uin":"289099750"}
09:39:12 SILL ==P==A==D==P==L==U==S==<GRPC DATA>==P==A==D==P==L==U==S==

09:39:12 SILL PuppetPadplus onRoomJoinEvent(1597212004)
09:39:12 SILL PuppetPadplus onRoomLeaveEvent(1597212004)
09:39:12 SILL rawPayload: {"content":"<sysmsg type=\"functionmsg\">\n<functionmsg>\n<cgi>/cgi-bin/micromsg-bin/pullfunctionmsg</cgi>\n<cmdid>614</cmdid>\n<functionmsgid>MMKANYIKAN_REDDOT_1597212300</functionmsgid>\n<retryinterval>150</retryinterval>\n<retrycount>3</retrycount>\n<custombuff>YImkAXIKMTU5NzIxMjMwMHoGd2VpeGluigEcTU1LQU5ZSUtBTl9SRURET1RfMTU5NzIxMjMwMKoBWHBlTUhiTDIvWHhTK1JZcldNTmtMeFdFRWpjY1gvNkErN0VoUHcyR0VrcCtOSTBrUVR1eGtJTXdMUFZyR3gvZWwvZDVZZE9lVVVadWRGTVl3NVJpMHJBPT0=</custombuff>\n<businessid>21001</businessid>\n<actiontime>1597212004</actiontime>\n<functionmsgversion>2</functionmsgversion>\n</functionmsg>\n</sysmsg>","createTime":1597801129001,"fromUserName":"weixin","imgBuf":"","imgStatus":1,"l1MsgType":5,"msgId":"1597212004","msgSource":"","msgSourceCd":2,"msgType":10002,"newMsgId":1597212004,"pushContent":"","status":3,"toUserName":"wxid_orp7dihe2pm112","uin":"289099750","wechatUserName":"wxid_orp7dihe2pm112"}
09:39:12 SILL PuppetPadplus onRoomTopicEvent(1597212004)
(node:68368) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'sysmsgtemplate' of undefined
    at Object.<anonymous> (/Users/suchang/Desktop/PROJECT/wechaty-related-project/wechaty-puppet-padplus/src/pure-function-helpers/room-event-leave-message-parser.ts:66:34)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/suchang/Desktop/PROJECT/wechaty-related-project/wechaty-puppet-padplus/dist/src/pure-function-helpers/room-event-leave-message-parser.js:5:58)
(node:68368) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
```

</details>

## 7. Additional context

[bug]

**Comment by su-chang** [comment]
Already resolved in `wechaty-puppet-padplus@0.7.37`.
