### ISSUE TITLE
发送消息提示no message rawPayload for message id

### ISSUE THREAD

**Issue by iguxiaobei** [wechaty/wechaty-puppet-padplus#303]
> Important：Please file the issue follow the template, or we won't help you to solve the problem.

## 0. Report Issue Guide

1. Please run the following command and check whether the problem has been fixed：

```
npm install wechaty-puppet-padlus@next
```

2. Please search in the issue first, and make sure your problem had not been reported before

## 1. Versions

- What is your wechaty version?
Answer:

wechaty@0.47.9

- What is your wechaty-puppet-padplus version?
Answer:

wechaty-puppet-padplus@0.7.36

- What is your node version? (run `node --version`)
Answer:

v10.15.0

- What os are you using
Answer:

Linux 

## 2. Describe the bug

Give a clear and concise description of what the bug is.

发消息到群里失败，提示no message rawPayload for message id 50945345

## 3. To Reproduce

This part is very important: if you can not provide any reproduce steps, then the problem will be very hard to be recognized.

1. run '...'
2. ...
3. ...

## 4. Expected behavior

Give a clear and concise description of what you expected to happen.

## 5. Actual behavior

If applicable, add screenshots to help explain your problem. But do not paste log screenshots here.

## 6. Full Output Logs

Set env `WECHATY_LOG=silly` in order to set log level to silly, then we can get the full log (If you dosen't set log env, log level is info as default, we cannot get the full log)

**We need full log instead of log screenshot or log fragments!**

<details>
<summary>
17:32:29 ERR Broadcast doBroadcast() error:
Error: no message rawPayload for message id 4224880293195382836
    at PuppetPadplus.<anonymous> (/xiaoju-bot/node_modules/wechaty-puppet-padplus/dist/src/puppet-padplus.js:1144:23)
    at Generator.next (<anonymous>)
    at fulfilled (/xiaoju-bot/node_modules/wechaty-puppet-padplus/dist/src/puppet-padplus.js:5:58)
17:32:33 ERR Config ###########################
17:32:33 ERR Config unhandledRejection: Error: get contact timeout [object Promise]
17:32:33 ERR Config ###########################
17:32:33 ERR Config process.on(unhandledRejection) promise.catch(get contact timeout)
Config Error: get contact timeout
    at Timeout.setTimeout [as _onTimeout] (/xiaoju-bot/node_modules/wechaty-puppet-padplus/dist/src/padplus-manager/padplus-manager.js:1014:57)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
(node:9) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 67)
17:32:34 INFO ConfigManager receive maintain mode heartbeat.
17:32:58 ERR PuppetPadplus messageRawPayload(7498498708342440173) manager.cacheManager.getMessage(7498498708342440173) return nothing.
17:32:58 ERR Broadcast doBroadcast() error:
Error: no message rawPayload for message id 7498498708342440173
    at PuppetPadplus.<anonymous> (/xiaoju-bot/node_modules/wechaty-puppet-padplus/dist/src/puppet-padplus.js:1144:23)
    at Generator.next (<anonymous>)
    at fulfilled (/xiaoju-bot/node_modules/wechaty-puppet-padplus/dist/src/puppet-padplus.js:5:58)
17:33:00 INFO 检测到有人离群: "大井峪小学", leavers: "茹", removed by "茹"
17:33:00 WARN Wechaty self() DEPRECATED. use userSelf() instead.
17:33:00 INFO Sync room leave system message
17:33:00 ERR roomLeave.syncRoomLeaveMessage removerAliasInRoom
17:33:00 ERR roomLeave.syncRoomLeaveMessage leaverAliasInRoom
17:33:18 ERR PuppetPadplus messageRawPayload(5097648639437526624) manager.cacheManager.getMessage(5097648639437526624) return nothing.
17:33:18 ERR Broadcast doBroadcast() error:
Error: no message rawPayload for message id 5097648639437526624
    at PuppetPadplus.<anonymous> (/xiaoju-bot/node_modules/wechaty-puppet-padplus/dist/src/puppet-padplus.js:1144:23)
    at Generator.next (<anonymous>)
    at fulfilled (/xiaoju-bot/node_modules/wechaty-puppet-padplus/dist/src/puppet-padplus.js:5:58)
17:33:22 ERR Config ###########################
17:33:22 ERR Config unhandledRejection: Error: get contact timeout [object Promise]
17:33:22 ERR Config ###########################
17:33:22 ERR Config process.on(unhandledRejection) promise.catch(get contact timeout)
Config Error: get contact timeout
    at Timeout.setTimeout [as _onTimeout] (/xiaoju-bot/node_modules/wechaty-puppet-padplus/dist/src/padplus-manager/padplus-manager.js:1014:57)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
(node:9) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 68)
17:33:34 INFO ConfigManager receive maintain mode heartbeat.
17:33:55 ERR Config ###########################
17:33:55 ERR Config unhandledRejection: Error: get contact timeout [object Promise]
17:33:55 ERR Config ###########################
17:33:55 ERR Config process.on(unhandledRejection) promise.catch(get contact timeout)
Config Error: get contact timeout
    at Timeout.setTimeout [as _onTimeout] (/xiaoju-bot/node_modules/wechaty-puppet-padplus/dist/src/padplus-manager/padplus-manager.js:1014:57)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
(node:9) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 69)
17:34:20 ERR Config ###########################
17:34:20 ERR Config unhandledRejection: Error: get contact timeout [object Promise]
17:34:20 ERR Config ###########################
17:34:20 ERR Config process.on(unhandledRejection) promise.catch(get contact timeout)
Config Error: get contact timeout
    at Timeout.setTimeout [as _onTimeout] (/xiaoju-bot/node_modules/wechaty-puppet-padplus/dist/src/padplus-manager/padplus-manager.js:1014:57)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
(node:9) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 70)
</summary>

```shell
$ WECHATY_LOG=silly node yourbot.js

Question: Paste your FULL(DO NOT ONLY PROVIDE FRAGMENTS) log messages
Answer:

```

</details>

## 7. Additional context

[bug]

**Comment by su-chang** [comment]
Could you please provide more info about this problem?

1. the reproduce step of this issue
2. the params of request `Send Message`

It seem that `padplus` can not create this type of message payload successfully, so the message payload is empty.

**Comment by iguxiaobei** [comment]
> Could you please provide more info about this problem?
> 
> 1. the reproduce step of this issue
> 2. the params of request `Send Message`
> 
> It seem that `padplus` can not create this type of message payload successfully, so the message payload is empty.

偶发，不能稳定复现，但是最新的有比较详细的日志

```shell
17:20:49 VERB Room topic()
17:20:49 VERB Room owner()
17:20:49 SILL Room memberAll()
17:20:49 VERB Room memberList()
17:20:49 SILL PuppetPadplus roomMemberList(19454002033@chatroom)
17:20:49 VERB Puppet roomMemberPayload(roomId=19454002033@chatroom, memberId=wxid_9weqll65378822)
17:20:49 VERB Contact friend()
17:20:49 VERB Puppet roomMemberPayload(roomId=19454002033@chatroom, memberId=wxid_f2pm1uhjj5bg22)
17:20:49 VERB Contact friend()
17:20:49 VERB Puppet roomMemberPayload(roomId=19454002033@chatroom, memberId=pei1725)
17:20:49 VERB Contact friend()
17:20:49 VERB Puppet roomMemberPayload(roomId=19454002033@chatroom, memberId=wxid_yfhiwwtmyyvf22)
17:20:49 VERB Contact friend()
17:20:49 VERB Puppet roomMemberPayload(roomId=19454002033@chatroom, memberId=wxid_gd27xtro95ut22)
17:20:49 VERB Contact friend()
17:20:49 VERB Room say(FileBox#Url<新高一二维码.jpg>, )
17:20:49 SILL PuppetPadplus messageSendFile(19454002033@chatroom)
17:20:49 SILL PuppetPadplus file url : https://s3.cn-north-1.amazonaws.com.cn/xiaoju-material/public/rc-upload-1598314558711-14_1598320351144_%E6%96%B0%E9%AB%98%E4%B8%80%E4%BA%8C%E7%BB%B4%E7%A0%81.jpg
17:20:49 SILL PuppetPadplus fileType image/jpeg
17:20:49 VERB Puppet selfId()
17:20:49 VERB PadplusManager sendFile()
17:20:49 VERB PadplusMessage sendFile()
17:20:49 SILL RequestClient request()
17:20:49 SILL DedupeApi dedupe() no need to dedupe api SEND_FILE.
17:20:49 SILL GRPC_GATEWAY GRPC Request ApiType: SEND_FILE
17:20:49 VERB Message static load(8451822463770270607)
17:20:49 VERB Message constructor(8451822463770270607) for class WechatifiedMessage
17:20:49 VERB Message ready()
17:20:49 VERB Puppet messagePayload(8451822463770270607)
17:20:49 SILL Puppet messagePayloadCache(8451822463770270607) cache MISS
17:20:49 SILL PuppetPadplus messageRawPayload(8451822463770270607)
17:20:49 ERR PuppetPadplus messageRawPayload(8451822463770270607) manager.cacheManager.getMessage(8451822463770270607) return nothing.
17:20:49 VERB Broadcast 群发任务暂停(materialInterval),时间:6秒
17:20:49 ERR Broadcast doBroadcast() error:
Error: no message rawPayload for message id 8451822463770270607
    at PuppetPadplus.<anonymous> (/xiaoju-bot/node_modules/wechaty-puppet-padplus/dist/src/puppet-padplus.js:1153:23)
    at Generator.next (<anonymous>)
    at fulfilled (/xiaoju-bot/node_modules/wechaty-puppet-padplus/dist/src/puppet-padplus.js:5:58)
17:20:55 VERB Broadcast sendMessage({"_id":"5f48b4a3bf5545003a01ba34","jobId":"5f48b4a0bf5545003a01b9cf","type":1,"botId":"5f12ab381dbb13003e47d9b5","roomId":"19454002033@chatroom","roomTopic":"洪洞马头学校在线考试技术支持群","status":0,"content":[{"name":"新高一","type":0,"content":{"text":"今晚7点直播中~~~[Meditate]\n     【新教材高一】名师训练营，今晚准时19：00开播，名师线上课堂，教你轻松学英语和物理[耶]，今晚7点开播，记得点击学习啦。"}},{"name":"新高一二维码.jpg","type":1,"content":{"url":"https://s3.cn-north-1.amazonaws.com.cn/xiaoju-material/public/rc-upload-1598314558711-14_1598320351144_%E6%96%B0%E9%AB%98%E4%B8%80%E4%BA%8C%E7%BB%B4%E7%A0%81.jpg","size":969456}},{"name":"新高一训练营","type":2,"content":{"sourceUrl":"https://appqbpfad7q3192.h5.xiaoeknow.com/v1/course/column/p_5f3f92bee4b0dd4d974a6d8f?type=3&share_user_id=u_5f309d1b36daf_UyvxMziBPW&share_type=2&scene=%E5%88%86%E4%BA%AB&entry=2&entry_type=2001&from=groupmessage&is_redirect=1","title":"新高一训练营","summary":"新高一训练营\n8月25日-8月28日 每天 19:00-20:00 共4节课 线上直播 免费观看 支持回放","imageUrl":"https://s3.cn-north-1.amazonaws.com.cn/xiaoju-material/public/rc-upload-1598314558711-30_1598321332620_%E6%96%B0%E9%AB%98%E4%B8%80.jpg"}}],"createdBy":"5e70231a127b600059e81b56"}, {"name":"新高一训练营","type":2,"content":{"sourceUrl":"https://appqbpfad7q3192.h5.xiaoeknow.com/v1/course/column/p_5f3f92bee4b0dd4d974a6d8f?type=3&share_user_id=u_5f309d1b36daf_UyvxMziBPW&share_type=2&scene=%E5%88%86%E4%BA%AB&entry=2&entry_type=2001&from=groupmessage&is_redirect=1","title":"新高一训练营","summary":"新高一训练营\n8月25日-8月28日 每天 19:00-20:00 共4节课 线上直播 免费观看 支持回放","imageUrl":"https://s3.cn-north-1.amazonaws.com.cn/xiaoju-material/public/rc-upload-1598314558711-30_1598321332620_%E6%96%B0%E9%AB%98%E4%B8%80.jpg"}})
17:20:55 VERB Room topic()
17:20:55 VERB Room owner()
17:20:55 SILL Room memberAll()
17:20:55 VERB Room memberList()
17:20:55 SILL PuppetPadplus roomMemberList(19454002033@chatroom)
17:20:55 VERB Puppet roomMemberPayload(roomId=19454002033@chatroom, memberId=wxid_9weqll65378822)
17:20:55 VERB Contact friend()
17:20:55 VERB Puppet roomMemberPayload(roomId=19454002033@chatroom, memberId=wxid_f2pm1uhjj5bg22)
17:20:55 VERB Contact friend()
17:20:55 VERB Puppet roomMemberPayload(roomId=19454002033@chatroom, memberId=pei1725)
17:20:55 VERB Contact friend()
17:20:55 VERB Puppet roomMemberPayload(roomId=19454002033@chatroom, memberId=wxid_yfhiwwtmyyvf22)
17:20:55 VERB Contact friend()
17:20:55 VERB Puppet roomMemberPayload(roomId=19454002033@chatroom, memberId=wxid_gd27xtro95ut22)
17:20:55 VERB Contact friend()
17:20:55 VERB UrlLink constructor()
17:20:55 VERB Room say(UrlLink<https://appqbpfad7q3192.h5.xiaoeknow.com/v1/course/column/p_5f3f92bee4b0dd4d974a6d8f?type=3&share_user_id=u_5f309d1b36daf_UyvxMziBPW&share_type=2&scene=%E5%88%86%E4%BA%AB&entry=2&entry_type=2001&from=groupmessage&is_redirect=1>, )
17:20:55 SILL PuppetPadplus messageSendUrl(19454002033@chatroom)
17:20:55 VERB Puppet selfId()
17:20:55 VERB PadplusManager sendUrlLink()
17:20:55 VERB PadplusMessage sendUrlLink()
17:20:55 VERB PadplusMessage sendMessage()
17:20:55 SILL RequestClient request()
17:20:55 SILL DedupeApi dedupe() no need to dedupe api SEND_MESSAGE.
17:20:55 SILL GRPC_GATEWAY GRPC Request ApiType: SEND_MESSAGE
17:20:56 VERB Message static load(8150185227366582540)
17:20:56 VERB Message constructor(8150185227366582540) for class WechatifiedMessage
17:20:56 VERB Message ready()
17:20:56 VERB Puppet messagePayload(8150185227366582540)
17:20:56 SILL Puppet messagePayloadCache(8150185227366582540) cache MISS
17:20:56 SILL PuppetPadplus messageRawPayload(8150185227366582540)
17:20:56 ERR PuppetPadplus messageRawPayload(8150185227366582540) manager.cacheManager.getMessage(8150185227366582540) return nothing.
17:20:56 ERR Broadcast doBroadcast() error:
Error: no message rawPayload for message id 8150185227366582540
    at PuppetPadplus.<anonymous> (/xiaoju-bot/node_modules/wechaty-puppet-padplus/dist/src/puppet-padplus.js:1153:23)
    at Generator.next (<anonymous>)
    at fulfilled (/xiaoju-bot/node_modules/wechaty-puppet-padplus/dist/src/puppet-padplus.js:5:58)
17:20:56 VERB Broadcast updateSentStatus([object Object], false)
17:20:56 VERB Broadcast 群发任务暂停(chatInterval),时间:6秒
17:21:00 SILL Check status: ::ffff:68.79.56.168
```

**Comment by iguxiaobei** [comment]
> Could you please provide more info about this problem?
> 
> 1. the reproduce step of this issue
> 2. the params of request `Send Message`
> 
> It seem that `padplus` can not create this type of message payload successfully, so the message payload is empty.

1. 客户群发出现的问题，所以没有固定的复现步骤
2. 发送的内容是一个文字，一个图片，一个链接，不确定哪个出的这个问题，参数如下

```json
[
  {
    "text" : "今晚7点直播中~~~[Meditate]\n     【新高一】名师训练营，今晚准时19：00开播，名师教你如何轻松学英语和物理[耶]，马上开播，赶快点击学习啦。"
  },
  {
     "url" : "https://s3.cn-north-1.amazonaws.com.cn/xiaoju-material/public/rc-upload-1598314558711-14_1598320351144_%E6%96%B0%E9%AB%98%E4%B8%80%E4%BA%8C%E7%BB%B4%E7%A0%81.jpg",
  },
  {
    "sourceUrl" : "https://appqbpfad7q3192.h5.xiaoeknow.com/v1/course/column/p_5f3f92bee4b0dd4d974a6d8f?type=3&share_user_id=u_5f309d1b36daf_UyvxMziBPW&share_type=2&scene=%E5%88%86%E4%BA%AB&entry=2&entry_type=2001&from=groupmessage&is_redirect=1",
    "title" : "新高一训练营",
    "summary" : "新高一训练营\n8月25日-8月28日 每天 19:00-20:00 共4节课 线上直播 免费观看 支持回放",
    "imageUrl" : "https://s3.cn-north-1.amazonaws.com.cn/xiaoju-material/public/rc-upload-1598314558711-30_1598321332620_%E6%96%B0%E9%AB%98%E4%B8%80.jpg"
}]
```
