### ISSUE TITLE
Error: Can not get media data url by this message id: 3381952114455636890

### ISSUE THREAD

**Issue by guoxiangke** [wechaty/wechaty-puppet-padplus#304]
```
(node:74130) UnhandledPromiseRejectionWarning: Error: Can not get media data url by this message id: 3381952114455636890
    at PuppetPadplus.<anonymous> (/Users/dale/Sites/wechaty-nuxt/node_modules/wechaty-puppet-padplus/src/puppet-padplus.ts:719:17)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/dale/Sites/wechaty-nuxt/node_modules/wechaty-puppet-padplus/dist/src/puppet-padplus.js:5:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by su-chang** [comment]
Could you please provide some reproduce steps about this issue?
