### ISSUE TITLE
[Room] Failed to parse sysmsg type: NewXmlChatRoomAccessVerifyApplication

### ISSUE THREAD

**Issue by wuying8** [wechaty/wechaty-puppet-padplus#35]
Failed to parse sysmsg type: NewXmlChatRoomAccessVerifyApplication, it will get the following error:

## Sysmsg
```
14:59:58 SILL GRPC_GATEWAY responseType: 30, data : {"Status":3,"CreateTime":1569826798187,"FileName":"","NewMsgId":3972781197305776618,"FromMemberUserName":"22818451918@chatroom","msgSourceCd":2,"ToUserName":"wxid_u6t19axpxman22","MsgType":10002,"L1MsgType":5,"ImgStatus":1,"wechatUserName":"wxid_u6t19axpxman22","MsgId":"3972781197305776618","MsgSource":"","PushContent":"","ImgBuf":"","fromMemberUserName":"22818451918@chatroom","Content":"22818451918@chatroom:\n<sysmsg type=\"NewXmlChatRoomAccessVerifyApplication\">\n\t<NewXmlChatRoomAccessVerifyApplication>\n\t\t<text>
<![CDATA[\"J H R\"想邀请1位朋友加入群聊]]>
</text>\n\t\t<link>\n\t\t\t<scene>roomaccessapplycheck_approve</scene>\n\t\t\t<text>
<![CDATA[  去确认]]></text>\n\t\t\t<ticket><![CDATA[AwAAAAEAAADwMssBnVuYS11PL1mi+UXmgsI4ZbOvM/gmHGTX35GATxfKCkGmNuW2YbowJjuKpnbKwZK/]]></ticket>\n\t\t\t<invitationreason><![CDATA[666]]></invitationreason>\n\t\t\t<inviterusername><![CDATA[wuying8]]></inviterusername>\n\t\t\t<memberlist>\n\t\t\t\t<memberlistsize>1</memberlistsize>\n\t\t\t\t<member>\n\t\t\t\t\t<username><![CDATA[wxid_4cfx5i8vx2622]]></username>\n\t\t\t\t\t<nickname><![CDATA[控寄寄几]]></nickname>\n\t\t\t\t\t
<headimgurl><![CDATA[http://wx.qlogo.cn/mmhead/ver_1/kkgvnyTNRu2wXjKj0tPdZicje3haAMSMPEib5z3jSx26MBVzwl1qvoib7s1AUY8iaPFia5pv2ScT6iakEwJdOibHZnjs24VneVBoAKdnVhAr9jp7e4/132]]></headimgurl>\n\t\t\t\t\t<quitchatroominfo>
<![CDATA[曾退出群聊,]]></quitchatroominfo>\n\t\t\t\t</member>\n\t\t\t</memberlist>\n\t\t</link>\n\t\t<RoomName><![CDATA[22818451918@chatroom]]></RoomName>\n\t</NewXmlChatRoomAccessVerifyApplication>\n</sysmsg>\n","FromUserName":"22818451918@chatroom","Uin":"3682263892"}
14:59:58 SILL ==P==A==D==P==L==U==S==<GRPC DATA>==P==A==D==P==L==U==S==
```

Error
```
Error: unknown jsonPayload sysmsg type: NewXmlChatRoomAccessVerifyApplication
    at Object.<anonymous> (/xio_bot/node_modules/wechaty-puppet-padplus/src/pure-function-helpers/room-event-join-message-parser.ts:143:15)
    at Generator.next (<anonymous>)
    at fulfilled (/xio_bot/node_modules/wechaty-puppet-padplus/dist/src/pure-function-helpers/room-event-join-message-parser.js:5:58)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
Error: unknown jsonPayload sysmsg type: NewXmlChatRoomAccessVerifyApplication
    at Object.<anonymous> (/xio_bot/node_modules/wechaty-puppet-padplus/src/pure-function-helpers/room-event-join-message-parser.ts:143:15)
    at Generator.next (<anonymous>)
    at fulfilled (/xio_bot/node_modules/wechaty-puppet-padplus/dist/src/pure-function-helpers/room-event-join-message-parser.js:5:58)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
14:59:58 ERR Config ###########################
14:59:58 ERR Config unhandledRejection: Error: unknown jsonPayload sysmsg type: NewXmlChatRoomAccessVerifyApplication [object Promise]
14:59:58 ERR Config ###########################
```

**Comment by su-chang** [comment]
Already resolved.

Please update `wechaty-puppet-padplus@latest`.
