### ISSUE TITLE
"Segmentation fault: 11" when logout

### ISSUE THREAD

**Issue by lx1990** [wechaty/wechaty-puppet-padplus#36]
## 1. Versions

- What is your wechaty version?
Answer: 0.28.3

- What is your wechaty-puppet-padplus version?
Answer: 0.0.124

- What is your node version? (run `node --version`)
Answer: 10.15.2

- What os are you using
Answer: macOS 10.14.5

## 2. Describe the bug

when I log out, sometimes the process will be stopped

## 3. To Reproduce

1. Scan the QRcode to log in
2. Click on the phone to log out 
3. sometimes this error occurs

## 4. Expected behavior

service restart and resend QRcode and I can log in by scanning it

## 5. Actual behavior

The process is stopped because of  `Segmentation fault: 11`(sometimes)

## 6. Full Output Logs

<details>
<summary>
Show Logs
</summary>

```shell
11:32:07 SILL ==P==A==D==P==L==U==S==<GRPC DATA>==P==A==D==P==L==U==S== 
11:32:07 SILL GRPC_GATEWAY responseType: 13, data : {"code":200,"uin":"69261405","message":"你已退出微信","mqType":1100}
11:32:07 SILL ==P==A==D==P==L==U==S==<GRPC DATA>==P==A==D==P==L==U==S==
 
Bot error: Error: PADPLUS_ERROR EXIT 你已退出微信
    at PuppetPadplus.puppet.on.error (/Users/leo/Ricepo/ricepobot/node_modules/wechaty/src/wechaty.ts:611:32)
    at PuppetPadplus.emit (events.js:189:13)
    at PuppetPadplus.EventEmitter.emit (domain.js:441:20)
    at PuppetPadplus.emit (/Users/leo/Ricepo/ricepobot/node_modules/wechaty-puppet/src/puppet.ts:282:18)
    at PadplusManager.manager.on (/Users/leo/Ricepo/ricepobot/node_modules/wechaty-puppet-padplus/src/puppet-padplus.ts:109:12)
    at PadplusManager.on.args (/Users/leo/Ricepo/ricepobot/node_modules/wechaty-puppet-padplus/src/padplus-manager/padplus-manager.ts:183:18)
    at PadplusManager.emit (events.js:189:13)
    at PadplusManager.EventEmitter.emit (domain.js:441:20)
    at PadplusManager.emit (/Users/leo/Ricepo/ricepobot/node_modules/wechaty-puppet-padplus/src/padplus-manager/padplus-manager.ts:164:18)
    at PadplusManager.<anonymous> (/Users/leo/Ricepo/ricepobot/node_modules/wechaty-puppet-padplus/src/padplus-manager/padplus-manager.ts:533:22)
    at Generator.next (<anonymous>)
    at /Users/leo/Ricepo/ricepobot/node_modules/wechaty-puppet-padplus/dist/src/padplus-manager/padplus-manager.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/leo/Ricepo/ricepobot/node_modules/wechaty-puppet-padplus/dist/src/padplus-manager/padplus-manager.js:4:12)
    at GrpcEventEmitter.grpcGatewayEmitter.on (/Users/leo/Ricepo/ricepobot/node_modules/wechaty-puppet-padplus/src/padplus-manager/padplus-manager.ts:352:66)
    at GrpcEventEmitter.emit (events.js:189:13)
    at GrpcEventEmitter.EventEmitter.emit (domain.js:441:20)
    at GrpcGateway.<anonymous> (/Users/leo/Ricepo/ricepobot/node_modules/wechaty-puppet-padplus/src/server-manager/grpc-gateway.ts:475:23)
    at Generator.next (<anonymous>)
    at /Users/leo/Ricepo/ricepobot/node_modules/wechaty-puppet-padplus/dist/src/server-manager/grpc-gateway.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/leo/Ricepo/ricepobot/node_modules/wechaty-puppet-padplus/dist/src/server-manager/grpc-gateway.js:4:12)
    at ClientReadableStream.stream.on (/Users/leo/Ricepo/ricepobot/node_modules/wechaty-puppet-padplus/src/server-manager/grpc-gateway.ts:398:54)
    at ClientReadableStream.emit (events.js:189:13)
    at ClientReadableStream.EventEmitter.emit (domain.js:441:20)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)
    at ClientReadableStream.Readable.push (_stream_readable.js:220:10)
    at Object.onReceiveMessage (/Users/leo/Ricepo/ricepobot/node_modules/grpc/src/client_interceptors.js:1263:19)
    at InterceptingListener.recvMessageWithContext (/Users/leo/Ricepo/ricepobot/node_modules/grpc/src/client_interceptors.js:607:19)
    at /Users/leo/Ricepo/ricepobot/node_modules/grpc/src/client_interceptors.js:707:14
11:32:07 SILL REQUEST request()
11:32:07 SILL GRPC_GATEWAY GRPC Request ApiType: 1
11:32:07 SILL ==P==A==D==P==L==U==S==<GRPC DATA>==P==A==D==P==L==U==S== 
11:32:07 SILL GRPC_GATEWAY responseType: 13, data : {"code":200,"uin":"69261405","message":"重连失败已被下线","mqType":1100}
11:32:07 SILL ==P==A==D==P==L==U==S==<GRPC DATA>==P==A==D==P==L==U==S==
 
Bot error: Error: PADPLUS_ERROR EXIT 重连失败已被下线
    at PuppetPadplus.puppet.on.error (/Users/leo/Ricepo/ricepobot/node_modules/wechaty/src/wechaty.ts:611:32)
    at PuppetPadplus.emit (events.js:189:13)
    at PuppetPadplus.EventEmitter.emit (domain.js:441:20)
    at PuppetPadplus.emit (/Users/leo/Ricepo/ricepobot/node_modules/wechaty-puppet/src/puppet.ts:282:18)
    at PadplusManager.manager.on (/Users/leo/Ricepo/ricepobot/node_modules/wechaty-puppet-padplus/src/puppet-padplus.ts:109:12)
    at PadplusManager.on.args (/Users/leo/Ricepo/ricepobot/node_modules/wechaty-puppet-padplus/src/padplus-manager/padplus-manager.ts:183:18)
    at PadplusManager.emit (events.js:189:13)
    at PadplusManager.EventEmitter.emit (domain.js:441:20)
    at PadplusManager.emit (/Users/leo/Ricepo/ricepobot/node_modules/wechaty-puppet-padplus/src/padplus-manager/padplus-manager.ts:164:18)
    at PadplusManager.<anonymous> (/Users/leo/Ricepo/ricepobot/node_modules/wechaty-puppet-padplus/src/padplus-manager/padplus-manager.ts:533:22)
    at Generator.next (<anonymous>)
    at /Users/leo/Ricepo/ricepobot/node_modules/wechaty-puppet-padplus/dist/src/padplus-manager/padplus-manager.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/leo/Ricepo/ricepobot/node_modules/wechaty-puppet-padplus/dist/src/padplus-manager/padplus-manager.js:4:12)
    at GrpcEventEmitter.grpcGatewayEmitter.on (/Users/leo/Ricepo/ricepobot/node_modules/wechaty-puppet-padplus/src/padplus-manager/padplus-manager.ts:352:66)
    at GrpcEventEmitter.emit (events.js:189:13)
    at GrpcEventEmitter.EventEmitter.emit (domain.js:441:20)
    at GrpcGateway.<anonymous> (/Users/leo/Ricepo/ricepobot/node_modules/wechaty-puppet-padplus/src/server-manager/grpc-gateway.ts:475:23)
    at Generator.next (<anonymous>)
    at /Users/leo/Ricepo/ricepobot/node_modules/wechaty-puppet-padplus/dist/src/server-manager/grpc-gateway.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/leo/Ricepo/ricepobot/node_modules/wechaty-puppet-padplus/dist/src/server-manager/grpc-gateway.js:4:12)
    at ClientReadableStream.stream.on (/Users/leo/Ricepo/ricepobot/node_modules/wechaty-puppet-padplus/src/server-manager/grpc-gateway.ts:398:54)
    at ClientReadableStream.emit (events.js:189:13)
    at ClientReadableStream.EventEmitter.emit (domain.js:441:20)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)
    at ClientReadableStream.Readable.push (_stream_readable.js:220:10)
    at Object.onReceiveMessage (/Users/leo/Ricepo/ricepobot/node_modules/grpc/src/client_interceptors.js:1263:19)
    at InterceptingListener.recvMessageWithContext (/Users/leo/Ricepo/ricepobot/node_modules/grpc/src/client_interceptors.js:607:19)
    at /Users/leo/Ricepo/ricepobot/node_modules/grpc/src/client_interceptors.js:707:14
11:32:07 SILL REQUEST request()
11:32:07 SILL GRPC_GATEWAY GRPC Request ApiType: 1
11:32:07 SILL ==P==A==D==P==L==U==S==<GRPC DATA>==P==A==D==P==L==U==S== 
11:32:07 SILL GRPC_GATEWAY responseType: 13, data : {"code":200,"uin":"69261405","message":"重连失败已被下线","mqType":1100}
11:32:07 SILL ==P==A==D==P==L==U==S==<GRPC DATA>==P==A==D==P==L==U==S==
 
Bot error: Error: PADPLUS_ERROR EXIT 重连失败已被下线
    at PuppetPadplus.puppet.on.error (/Users/leo/Ricepo/ricepobot/node_modules/wechaty/src/wechaty.ts:611:32)
    at PuppetPadplus.emit (events.js:189:13)
    at PuppetPadplus.EventEmitter.emit (domain.js:441:20)
    at PuppetPadplus.emit (/Users/leo/Ricepo/ricepobot/node_modules/wechaty-puppet/src/puppet.ts:282:18)
    at PadplusManager.manager.on (/Users/leo/Ricepo/ricepobot/node_modules/wechaty-puppet-padplus/src/puppet-padplus.ts:109:12)
    at PadplusManager.on.args (/Users/leo/Ricepo/ricepobot/node_modules/wechaty-puppet-padplus/src/padplus-manager/padplus-manager.ts:183:18)
    at PadplusManager.emit (events.js:189:13)
    at PadplusManager.EventEmitter.emit (domain.js:441:20)
    at PadplusManager.emit (/Users/leo/Ricepo/ricepobot/node_modules/wechaty-puppet-padplus/src/padplus-manager/padplus-manager.ts:164:18)
    at PadplusManager.<anonymous> (/Users/leo/Ricepo/ricepobot/node_modules/wechaty-puppet-padplus/src/padplus-manager/padplus-manager.ts:533:22)
    at Generator.next (<anonymous>)
    at /Users/leo/Ricepo/ricepobot/node_modules/wechaty-puppet-padplus/dist/src/padplus-manager/padplus-manager.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/leo/Ricepo/ricepobot/node_modules/wechaty-puppet-padplus/dist/src/padplus-manager/padplus-manager.js:4:12)
    at GrpcEventEmitter.grpcGatewayEmitter.on (/Users/leo/Ricepo/ricepobot/node_modules/wechaty-puppet-padplus/src/padplus-manager/padplus-manager.ts:352:66)
    at GrpcEventEmitter.emit (events.js:189:13)
    at GrpcEventEmitter.EventEmitter.emit (domain.js:441:20)
    at GrpcGateway.<anonymous> (/Users/leo/Ricepo/ricepobot/node_modules/wechaty-puppet-padplus/src/server-manager/grpc-gateway.ts:475:23)
    at Generator.next (<anonymous>)
    at /Users/leo/Ricepo/ricepobot/node_modules/wechaty-puppet-padplus/dist/src/server-manager/grpc-gateway.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/leo/Ricepo/ricepobot/node_modules/wechaty-puppet-padplus/dist/src/server-manager/grpc-gateway.js:4:12)
    at ClientReadableStream.stream.on (/Users/leo/Ricepo/ricepobot/node_modules/wechaty-puppet-padplus/src/server-manager/grpc-gateway.ts:398:54)
    at ClientReadableStream.emit (events.js:189:13)
    at ClientReadableStream.EventEmitter.emit (domain.js:441:20)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)
    at ClientReadableStream.Readable.push (_stream_readable.js:220:10)
    at Object.onReceiveMessage (/Users/leo/Ricepo/ricepobot/node_modules/grpc/src/client_interceptors.js:1263:19)
    at InterceptingListener.recvMessageWithContext (/Users/leo/Ricepo/ricepobot/node_modules/grpc/src/client_interceptors.js:607:19)
    at /Users/leo/Ricepo/ricepobot/node_modules/grpc/src/client_interceptors.js:707:14
11:32:07 SILL REQUEST request()
11:32:07 SILL GRPC_GATEWAY GRPC Request ApiType: 1
11:32:07 SILL ==P==A==D==P==L==U==S==<GRPC DATA>==P==A==D==P==L==U==S== 
11:32:07 SILL GRPC_GATEWAY responseType: 13, data : {"code":200,"uin":"69261405","message":"重连失败已被下线","mqType":1100}
11:32:07 SILL ==P==A==D==P==L==U==S==<GRPC DATA>==P==A==D==P==L==U==S==
 
Bot error: Error: PADPLUS_ERROR EXIT 重连失败已被下线
    at PuppetPadplus.puppet.on.error (/Users/leo/Ricepo/ricepobot/node_modules/wechaty/src/wechaty.ts:611:32)
    at PuppetPadplus.emit (events.js:189:13)
    at PuppetPadplus.EventEmitter.emit (domain.js:441:20)
    at PuppetPadplus.emit (/Users/leo/Ricepo/ricepobot/node_modules/wechaty-puppet/src/puppet.ts:282:18)
    at PadplusManager.manager.on (/Users/leo/Ricepo/ricepobot/node_modules/wechaty-puppet-padplus/src/puppet-padplus.ts:109:12)
    at PadplusManager.on.args (/Users/leo/Ricepo/ricepobot/node_modules/wechaty-puppet-padplus/src/padplus-manager/padplus-manager.ts:183:18)
    at PadplusManager.emit (events.js:189:13)
    at PadplusManager.EventEmitter.emit (domain.js:441:20)
    at PadplusManager.emit (/Users/leo/Ricepo/ricepobot/node_modules/wechaty-puppet-padplus/src/padplus-manager/padplus-manager.ts:164:18)
    at PadplusManager.<anonymous> (/Users/leo/Ricepo/ricepobot/node_modules/wechaty-puppet-padplus/src/padplus-manager/padplus-manager.ts:533:22)
    at Generator.next (<anonymous>)
    at /Users/leo/Ricepo/ricepobot/node_modules/wechaty-puppet-padplus/dist/src/padplus-manager/padplus-manager.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/leo/Ricepo/ricepobot/node_modules/wechaty-puppet-padplus/dist/src/padplus-manager/padplus-manager.js:4:12)
    at GrpcEventEmitter.grpcGatewayEmitter.on (/Users/leo/Ricepo/ricepobot/node_modules/wechaty-puppet-padplus/src/padplus-manager/padplus-manager.ts:352:66)
    at GrpcEventEmitter.emit (events.js:189:13)
    at GrpcEventEmitter.EventEmitter.emit (domain.js:441:20)
    at GrpcGateway.<anonymous> (/Users/leo/Ricepo/ricepobot/node_modules/wechaty-puppet-padplus/src/server-manager/grpc-gateway.ts:475:23)
    at Generator.next (<anonymous>)
    at /Users/leo/Ricepo/ricepobot/node_modules/wechaty-puppet-padplus/dist/src/server-manager/grpc-gateway.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/leo/Ricepo/ricepobot/node_modules/wechaty-puppet-padplus/dist/src/server-manager/grpc-gateway.js:4:12)
    at ClientReadableStream.stream.on (/Users/leo/Ricepo/ricepobot/node_modules/wechaty-puppet-padplus/src/server-manager/grpc-gateway.ts:398:54)
    at ClientReadableStream.emit (events.js:189:13)
    at ClientReadableStream.EventEmitter.emit (domain.js:441:20)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)
    at ClientReadableStream.Readable.push (_stream_readable.js:220:10)
    at Object.onReceiveMessage (/Users/leo/Ricepo/ricepobot/node_modules/grpc/src/client_interceptors.js:1263:19)
    at InterceptingListener.recvMessageWithContext (/Users/leo/Ricepo/ricepobot/node_modules/grpc/src/client_interceptors.js:607:19)
    at /Users/leo/Ricepo/ricepobot/node_modules/grpc/src/client_interceptors.js:707:14
11:32:07 SILL REQUEST request()
11:32:07 SILL GRPC_GATEWAY GRPC Request ApiType: 1
11:32:07 SILL ==P==A==D==P==L==U==S==<GRPC DATA>==P==A==D==P==L==U==S== 
11:32:07 SILL GRPC_GATEWAY responseType: 13, data : {"code":200,"uin":"69261405","message":"重连失败已被下线","mqType":1100}
11:32:07 SILL ==P==A==D==P==L==U==S==<GRPC DATA>==P==A==D==P==L==U==S==
 
Bot error: Error: PADPLUS_ERROR EXIT 重连失败已被下线
    at PuppetPadplus.puppet.on.error (/Users/leo/Ricepo/ricepobot/node_modules/wechaty/src/wechaty.ts:611:32)
    at PuppetPadplus.emit (events.js:189:13)
    at PuppetPadplus.EventEmitter.emit (domain.js:441:20)
    at PuppetPadplus.emit (/Users/leo/Ricepo/ricepobot/node_modules/wechaty-puppet/src/puppet.ts:282:18)
    at PadplusManager.manager.on (/Users/leo/Ricepo/ricepobot/node_modules/wechaty-puppet-padplus/src/puppet-padplus.ts:109:12)
    at PadplusManager.on.args (/Users/leo/Ricepo/ricepobot/node_modules/wechaty-puppet-padplus/src/padplus-manager/padplus-manager.ts:183:18)
    at PadplusManager.emit (events.js:189:13)
    at PadplusManager.EventEmitter.emit (domain.js:441:20)
    at PadplusManager.emit (/Users/leo/Ricepo/ricepobot/node_modules/wechaty-puppet-padplus/src/padplus-manager/padplus-manager.ts:164:18)
    at PadplusManager.<anonymous> (/Users/leo/Ricepo/ricepobot/node_modules/wechaty-puppet-padplus/src/padplus-manager/padplus-manager.ts:533:22)
    at Generator.next (<anonymous>)
    at /Users/leo/Ricepo/ricepobot/node_modules/wechaty-puppet-padplus/dist/src/padplus-manager/padplus-manager.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/leo/Ricepo/ricepobot/node_modules/wechaty-puppet-padplus/dist/src/padplus-manager/padplus-manager.js:4:12)
    at GrpcEventEmitter.grpcGatewayEmitter.on (/Users/leo/Ricepo/ricepobot/node_modules/wechaty-puppet-padplus/src/padplus-manager/padplus-manager.ts:352:66)
    at GrpcEventEmitter.emit (events.js:189:13)
    at GrpcEventEmitter.EventEmitter.emit (domain.js:441:20)
    at GrpcGateway.<anonymous> (/Users/leo/Ricepo/ricepobot/node_modules/wechaty-puppet-padplus/src/server-manager/grpc-gateway.ts:475:23)
    at Generator.next (<anonymous>)
    at /Users/leo/Ricepo/ricepobot/node_modules/wechaty-puppet-padplus/dist/src/server-manager/grpc-gateway.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/leo/Ricepo/ricepobot/node_modules/wechaty-puppet-padplus/dist/src/server-manager/grpc-gateway.js:4:12)
    at ClientReadableStream.stream.on (/Users/leo/Ricepo/ricepobot/node_modules/wechaty-puppet-padplus/src/server-manager/grpc-gateway.ts:398:54)
    at ClientReadableStream.emit (events.js:189:13)
    at ClientReadableStream.EventEmitter.emit (domain.js:441:20)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)
    at ClientReadableStream.Readable.push (_stream_readable.js:220:10)
    at Object.onReceiveMessage (/Users/leo/Ricepo/ricepobot/node_modules/grpc/src/client_interceptors.js:1263:19)
    at InterceptingListener.recvMessageWithContext (/Users/leo/Ricepo/ricepobot/node_modules/grpc/src/client_interceptors.js:607:19)
    at /Users/leo/Ricepo/ricepobot/node_modules/grpc/src/client_interceptors.js:707:14
11:32:07 SILL REQUEST request()
11:32:07 SILL GRPC_GATEWAY GRPC Request ApiType: 1
11:32:07 SILL ==P==A==D==P==L==U==S==<GRPC DATA>==P==A==D==P==L==U==S== 
11:32:07 SILL GRPC_GATEWAY responseType: 13, data : {"code":200,"uin":"69261405","message":"重连失败已被下线","mqType":1100}
11:32:07 SILL ==P==A==D==P==L==U==S==<GRPC DATA>==P==A==D==P==L==U==S==
 
Bot error: Error: PADPLUS_ERROR EXIT 重连失败已被下线
    at PuppetPadplus.puppet.on.error (/Users/leo/Ricepo/ricepobot/node_modules/wechaty/src/wechaty.ts:611:32)
    at PuppetPadplus.emit (events.js:189:13)
    at PuppetPadplus.EventEmitter.emit (domain.js:441:20)
    at PuppetPadplus.emit (/Users/leo/Ricepo/ricepobot/node_modules/wechaty-puppet/src/puppet.ts:282:18)
    at PadplusManager.manager.on (/Users/leo/Ricepo/ricepobot/node_modules/wechaty-puppet-padplus/src/puppet-padplus.ts:109:12)
    at PadplusManager.on.args (/Users/leo/Ricepo/ricepobot/node_modules/wechaty-puppet-padplus/src/padplus-manager/padplus-manager.ts:183:18)
    at PadplusManager.emit (events.js:189:13)
    at PadplusManager.EventEmitter.emit (domain.js:441:20)
    at PadplusManager.emit (/Users/leo/Ricepo/ricepobot/node_modules/wechaty-puppet-padplus/src/padplus-manager/padplus-manager.ts:164:18)
    at PadplusManager.<anonymous> (/Users/leo/Ricepo/ricepobot/node_modules/wechaty-puppet-padplus/src/padplus-manager/padplus-manager.ts:533:22)
    at Generator.next (<anonymous>)
    at /Users/leo/Ricepo/ricepobot/node_modules/wechaty-puppet-padplus/dist/src/padplus-manager/padplus-manager.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/leo/Ricepo/ricepobot/node_modules/wechaty-puppet-padplus/dist/src/padplus-manager/padplus-manager.js:4:12)
    at GrpcEventEmitter.grpcGatewayEmitter.on (/Users/leo/Ricepo/ricepobot/node_modules/wechaty-puppet-padplus/src/padplus-manager/padplus-manager.ts:352:66)
    at GrpcEventEmitter.emit (events.js:189:13)
    at GrpcEventEmitter.EventEmitter.emit (domain.js:441:20)
    at GrpcGateway.<anonymous> (/Users/leo/Ricepo/ricepobot/node_modules/wechaty-puppet-padplus/src/server-manager/grpc-gateway.ts:475:23)
    at Generator.next (<anonymous>)
    at /Users/leo/Ricepo/ricepobot/node_modules/wechaty-puppet-padplus/dist/src/server-manager/grpc-gateway.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/leo/Ricepo/ricepobot/node_modules/wechaty-puppet-padplus/dist/src/server-manager/grpc-gateway.js:4:12)
    at ClientReadableStream.stream.on (/Users/leo/Ricepo/ricepobot/node_modules/wechaty-puppet-padplus/src/server-manager/grpc-gateway.ts:398:54)
    at ClientReadableStream.emit (events.js:189:13)
    at ClientReadableStream.EventEmitter.emit (domain.js:441:20)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)
    at ClientReadableStream.Readable.push (_stream_readable.js:220:10)
    at Object.onReceiveMessage (/Users/leo/Ricepo/ricepobot/node_modules/grpc/src/client_interceptors.js:1263:19)
    at InterceptingListener.recvMessageWithContext (/Users/leo/Ricepo/ricepobot/node_modules/grpc/src/client_interceptors.js:607:19)
    at /Users/leo/Ricepo/ricepobot/node_modules/grpc/src/client_interceptors.js:707:14
11:32:07 SILL REQUEST request()
11:32:07 SILL GRPC_GATEWAY GRPC Request ApiType: 1
11:32:27 VERB PUPPET_PADPLUS logout()
11:32:27 VERB Puppet selfId()
11:32:27 SILL Contact ready() @ Puppet#0<PuppetPadplus>(padplus)
11:32:27 SILL Contact ready() isReady() true
11:32:27 VERB PadplusManager logout()
11:32:27 SILL GRPC_GATEWAY stop()
11:32:27 SILL GRPC_GATEWAY GRPC Request ApiType: 5
Contact<username> logout
Contact<username> logout
11:32:27 VERB CacheManager release()
11:32:27 VERB CacheManager releaseCache()
11:32:27 SILL CacheManager releaseCache() closing caches ...
Segmentation fault: 11

```

</details>

## 7. Additional context

[bug]

**Comment by su-chang** [comment]
Already resolved.

Please update `wechaty-puppet-padplus@latest`
