### ISSUE TITLE
 Error: can not send message due to this error: Error: ApiType: 50 request timeout, requestId

### ISSUE THREAD

**Issue by PandaTsui** [wechaty/wechaty-puppet-padplus#51]
> Important：Please file the issue follow the template, or we won't help you to solve the problem.

## 0. Report Issue Guide

1. Please run the following command and check whether the problem has been fixed：

```
npm install wechaty-puppet-padlus@next
```

2. Please search in the issue first, and make sure your problem had not been reported before

## 1. Versions

- What is your wechaty version?
Answer:0.28.3

- What is your wechaty-puppet-padplus version?
Answer:0.0.126

- What is your node version? (run `node --version`)
Answer: 10.16.0

- What os are you using
Answer:  linux 

## 2. Describe the bug

没问题，项目在线上运行10几个小时后，发送群消息和个人消息的接口say()方法 就调不通了，之前一直可以通的。onmessage的监听是正常可用的。
报错内容：
```
 Error: can not send message due to this error: Error: ApiType: 50 request timeout, requestId: 4751929f-8867-4ffd-9678-78d110049a0b
at PadplusMessage.<anonymous> (/home/wwwroot/wechat-monitor/node_modules/wechaty-puppet-padplus/dist/src/padplus-manager/api-request/message.js:147:23)
 at Generator.throw (<anonymous>)
 at rejected (/home/wwwroot/wechat-monitor/node_modules/wechaty-puppet-padplus/dist/src/padplus-manager/api-request/message.js:6:65)
```

## 3. To Reproduce

错误代码定位：
```
// Send message (text, image, url, video, file, gif)
    sendMessage(selfId, receiverId, content, messageType, mentionListStr) {
        return __awaiter(this, void 0, void 0, function* () {
            config_1.log.verbose(PRE, `sendMessage()`);
            const data = {
                content: content,
                fromUserName: selfId,
                mentionListStr,
                messageType,
                toUserName: receiverId,
            };
            try {
                const res = yield this.requestClient.request({
                    apiType: PadPlusServer_pb_1.ApiType.SEND_MESSAGE,
                    data,
                });
                if (res) {
                    const msgDataStr = res.getData();
                    if (msgDataStr) {
                        const msgData = JSON.parse(msgDataStr);
                        return msgData;
                    }
                    else {
                        throw new Error(`can not parse message data from grpc`);
                    }
                }
                else {
                    throw new Error(`can not get response from grpc server`);
                }
            }
            catch (e) {
                // FIXME:这里报错的
                throw new Error(`can not send message due to this error: ${e}`); 
            }
        });
    }
```
## 4. other Info 
重启wechaty后恢复正常
[bug]

**Comment by su-chang** [comment]
Nothing update about this issue, it will be closed.
