### ISSUE TITLE
企业微信监听不到消息

### ISSUE THREAD

**Issue by wenh7788** [wechaty/wechaty-puppet-padplus#76]
(node:2364) UnhandledPromiseRejectionWarning: Error: get contact timeout
    at Timeout.setTimeout [as _onTimeout] (/Users/zxc/workspace/company/tnWechatyPadPlus/node_modules/wechaty-puppet-padplus/dist/src/padplus-manager/padplus-manager.js:747:57)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
(node:2364) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2364) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

报错如上~~，谢谢，不过这个东西可能暂时用不到，感觉支持下会好一些~~

**Comment by su-chang** [comment]
It's a new Feature, but we can not support now.

**Comment by VEADoc** [comment]
> It's a new Feature, but we can not support now.

请问现在是着手在开发了吗

**Comment by su-chang** [comment]
Sorry, it is not in our next plan.
